클라이언트 예외를 위한 Validator 추가
woowacourse-teams/2023-baton pull request #117
Opened 2023-07-26 10:52 UTC by shb03323

## 관련이슈

- resolved #115 

## 참고사항
없습니다.

2023-07-26 23:28 UTC, cookienc requested changes
굳👍👍

2023-07-26 23:28 UTC, cookienc commented on backend/baton/src/main/java/touch/baton/domain/common/exception/ClientErrorCode.java
> +    TAGS_ARE_NULL(HttpStatus.NOT_FOUND, "RP008", "태그 목록을 빈 값이라도 입력해주세요.");
태그가 null이면 입력을 안한거니까 Bad request 아닌가요?

2023-07-27 01:22 UTC, hyena0608 approved these changes
굿굿굿 고생하셨어요 🎉

2023-07-27 01:24 UTC, cookienc approved these changes
LGTM!

2023-07-27 01:25 UTC, merged