서포터 전체 조회 기술 태그 목록 추가 version-test
woowacourse-teams/2023-baton pull request #162
Opened 2023-07-31 10:13 UTC by eunbii0213

## 관련이슈

- resolved #157 

## 참고사항
서포터 전체 조회 기술 태그 목록 추가 version-test입니다.

2023-07-31 10:18 UTC, hyena0608 reviewed
조금 궁금한 부분들만 커멘트 남겨봤어!

2023-07-31 10:18 UTC, hyena0608 commented on backend/baton/src/main/java/touch/baton/domain/supporter/controller/response/SupporterResponse.java
> +                    supporter.getSupporterTechnicalTags().getSupporterTechnicalTags().toString()
```suggestion
                    supporter.getSupporterTechnicalTags().getSupporterTechnicalTags().toString()
```

`toString()`을 사용하는 이유가 궁금해 🤔

2023-07-31 10:18 UTC, hyena0608 commented on backend/baton/src/test/java/touch/baton/domain/supporter/SupporterTest.java
> +        Assertions.assertEquals(actualSecondTag, expectedSecondTag);
검증부가 여러 개 분리된 느낌인데 혹시 검증부를 한 번에 볼 수 있게 하는거는 어떻게 생각해? 😊

2023-07-31 23:07 UTC, cookienc requested changes

2023-07-31 23:07 UTC, cookienc commented on backend/baton/src/test/java/touch/baton/domain/supporter/SupporterTest.java
> +        Assertions.assertEquals(actualTags.size(), 2);
Assertions를 static import를 해줬으면 좋겠어! 그리고 검증이 여러개니까 assertAll()을 사용해보는건 어떨까?

2023-08-01 03:00 UTC, shb03323 approved these changes
LGTM!

2023-08-01 03:00 UTC, cookienc approved these changes
굿굿

2023-08-01 03:02 UTC, hyena0608 approved these changes

2023-08-01 03:16 UTC, merged