Github Social Login 1차 구현
woowacourse-teams/2023-baton pull request #164
Opened 2023-08-01 00:04 UTC by hyena0608

## 관련이슈

- resolved #163 

## 참고사항
- sub-be 업데이트 했습니다.
- 프로필 정보를 받아서 저장하는 부분까지 잘 됩니다.
- 보안 쪽 부분. 프론트에게 AccessToken을 JWT로 만들어서 헤더에 넣어서 전송하는지 바디에 전송할지 의견 궁금합니다.

이 코드와 흐름은 [말랑의 oauth 포스팅](https://ttl-blog.tistory.com/1434#%F0%9F%A7%90%204.%20%EB%B0%9B%EC%95%84%EC%98%A8%20%EC%A0%95%EB%B3%B4%EB%A5%BC%20%ED%86%B5%ED%95%B4%20%EB%A1%9C%EA%B7%B8%EC%9D%B8%EC%9D%84%20%EC%A7%84%ED%96%89%ED%95%9C%EB%8B%A4.%20%EC%9D%B4%EB%95%8C%20%ED%9A%8C%EC%9B%90%EA%B0%80%EC%9E%85%20%EB%90%98%EC%96%B4%EC%9E%88%EC%A7%80%20%EC%95%8A%EB%8B%A4%EB%A9%B4%20%ED%9A%8C%EC%9B%90%EA%B0%80%EC%9E%85%EB%8F%84%20%ED%95%A8%EA%BB%98%20%EC%A7%84%ED%96%89%ED%95%9C%EB%8B%A4.-1) 을 보고 했습니다.

동작은 아직 이쁘게 설명을 못해서 흐름만 그림으로 놓겠습니다.
첫 번째 그림은 Redirect 하는 부분이고
두 번째 그림은 AuthCode를 받아 AccessToken을 요청하고 AccessToken으로 부터 다시 프로필 정보를 요청하는 흐름입니다.
- Oauth만 이용해서 Github에 접근하여 프로필 정보를 가져오게 했습니다.
- JWT를 아직 사용하지 않아서 OauthController에서 OauthId를 반환하고 있습니다.
![image](https://github.com/woowacourse-teams/2023-baton/assets/82203978/f5a6c226-409f-4aac-87c6-0fab20d78b82)
![image](https://github.com/woowacourse-teams/2023-baton/assets/82203978/1fb77790-fc51-4de5-9836-e373556fd708)

2023-08-02 02:26 UTC, shb03323 commented on backend/baton/build.gradle
> +	implementation 'org.springframework.boot:spring-boot-starter-webflux'
웹플럭스 어디에 쓰시나요

2023-08-02 02:28 UTC, shb03323 commented on backend/baton/src/main/java/touch/baton/BatonApplication.java
> +@ConfigurationPropertiesScan
처음보는 어노테이션이네요 공부해보겠습니다.

2023-08-02 02:30 UTC, shb03323 commented on backend/baton/src/main/java/touch/baton/domain/oauth/AccessToken.java
> +}
어떤 accessToken인지 헷갈렸어요.
githubAccessToken 으로 이름을 변경하면 어떨까요?

2023-08-02 02:31 UTC, shb03323 commented on backend/baton/src/main/java/touch/baton/domain/oauth/AccessToken.java
> +}
또 한번 생성되면 절대 바뀌지 않는 값이라고 생각합니다.
final class에 대한 생각은 어떠세요?

2023-08-02 08:17 UTC, hyena0608 commented on backend/baton/src/main/java/touch/baton/domain/oauth/AccessToken.java
> +}
AccessToken은 소셜 로그인 모든 곳에서 쓰이는 곳이라서 GithubAccessToken이라고 클래스명을 수정하면 깃허브에만 한정되는거 같습니다.

final 클래스는 좋습니다 수정할게요!

2023-08-02 10:07 UTC, hyena0608 commented on backend/baton/build.gradle
> +	implementation 'org.springframework.boot:spring-boot-starter-webflux'
Spring6에 나온 Http Interface를 사용해서 바톤 서버에서 Authorization Server와 통신할 때 `WebClient`가 필요해서 사용했습니다. 

[스프링 공식 문서](https://docs.spring.io/spring-framework/docs/6.0.0/reference/html/integration.html#rest-http-interface)

2023-08-02 11:25 UTC, shb03323 commented on backend/baton/src/main/java/touch/baton/config/WebMvcConfig.java
> +                .allowedOrigins("http://localhost:3000")
수동 컨피규레이션 다시 적용하면 어떨까요?

2023-08-02 11:27 UTC, shb03323 commented on backend/baton/src/main/java/touch/baton/domain/common/exception/ClientErrorCode.java
> +    COMPANY_IS_NULL(HttpStatus.BAD_REQUEST, "OM001", "사용자의 회사 정보를 입력해주세요."),
논의가 필요한 부분이군요.

2023-08-02 11:46 UTC, shb03323 commented on backend/baton/src/main/java/touch/baton/domain/common/exception/ClientErrorCode.java
> +    JWT_SIGNATURE_IS_WRONG(HttpStatus.BAD_REQUEST, "JW", "시그니처가 다른 잘못된 JWT 입니다.");
jwt와 oauth를 구분하기 어려울 수 있을 것 같아요. 저는 email이 잘못된 것은 페이로드가 잘못된 것이기 때문에 jwt로 보고 있거든요.
+) 만료된 경우의 예외도 추가되어야 할 것 같습니다!
+) 잘못된 페이로드 예외도 추가되어야 할 것 같습니다!

2023-08-02 11:47 UTC, hyena0608 commented on backend/baton/src/main/java/touch/baton/config/WebMvcConfig.java
> +                .allowedOrigins("http://localhost:3000")
Credentials true로 열고 origin은 외부 변수 받도록 수정했습니다

2023-08-02 11:51 UTC, hyena0608 commented on backend/baton/src/main/java/touch/baton/domain/oauth/OauthType.java
> +    GITHUB;
테스트 설정 관련해서 인수 테스트를 한다고 가정 했을 때 Oauth까지 다 한 번에 테스트할지 아니면 외부 기능이라고 생각하고 Oauth를 Mocking으로 진행할지 이야기 해봐야 할 거 같습니다.

프로덕션 코드를 건드리지 않고 테스트 패키지 내부에서 해결해보고 싶은 생각입니다.

2023-08-02 14:31 UTC, shb03323 commented
oauth.controller 패키지 내부에 ArgumentResolver, 어노테이션, Converter가 있습니다.

에단의 방법처럼 config 안에 디랙토리를 만들고 관련 있는 객체들을 넣어 패키징하면 어떨까요?
controller 패키지 안에 controller와 관련 없는 객체들이 있는 것 같아서요.
+) ArgumentResolver는 애매한데, 다른 분들 생각이 궁금합니다.

2023-08-02 14:36 UTC, hyena0608 commented
> oauth.controller 패키지 내부에 ArgumentResolver, 어노테이션, Converter가 있습니다.
> 
> 에단의 방법처럼 config 안에 디랙토리를 만들고 관련 있는 객체들을 넣어 패키징하면 어떨까요? controller 패키지 안에 controller와 관련 없는 객체들이 있는 것 같아서요. +) ArgumentResolver는 애매한데, 다른 분들 생각이 궁금합니다.

저도 converter는 config 찬성합니다.
Annotation이랑 ArgumentResolver는 조금 애매한 감이 있네요.

저는 ArgumentResolver는 컨트롤러 계층에 더 가깝다고 생각해서 그렇게 두었고
Annotation도 컨트롤러 계층에서 사용하되 Auth 와 가장 가깝다고 생각해서 oauth 패키지에 두는 선택을 했습니다.

2023-08-02 14:37 UTC, shb03323 commented on backend/baton/build.gradle
> +	implementation 'org.springframework.boot:spring-boot-starter-webflux'
스프링 MVC 로는 불가능할까용...? (진짜 잘 몰라서)

우려되는 것이,
비슷한 기술인데 함께 쓴다는 것이 나중되면 짬뽕으로 쓸 수 있을 것 같아서요.
지금은 한 번 밖에 쓰지 않지만 어떤건 webflux를 쓰고 어떤건 spring mvc를 쓰면 유지보수 할 때 봐야할 것이 더 많아질 수도 있겠다는 생각이 듭니다.

2023-08-02 16:25 UTC, shin-mallang commented on backend/baton/build.gradle
> +	implementation 'org.springframework.boot:spring-boot-starter-webflux'
스프링부트 3.2 버전부터 WebClient대신 RestClinet를 제공해준다고 해서, 나중에 버전 업데이트 하면서 웹플럭스 의존성 지울 수 있을 것 같습니다.
https://docs.spring.io/spring-boot/docs/3.2.0-M1/reference/html//io.html#io.rest-client.restclient

2023-08-02 23:40 UTC, cookienc requested changes
로그인 기능 구현한 헤나 칭찬해🎉 로직은 주말에 공부해볼게ㅋㅋㅋ

2023-08-02 23:40 UTC, cookienc commented on backend/baton/src/main/java/touch/baton/domain/oauth/controller/AuthRunnerPrincipalArgumentResolver.java
> +        if (!authHeader.startsWith("Bearer ")) {
Bearer 반복되는데 상수화 어떠신가요?

2023-08-02 23:40 UTC, cookienc commented on backend/baton/src/main/java/touch/baton/domain/oauth/controller/AuthSupporterPrincipalArgumentResolver.java
> +        if (!authHeader.startsWith("Bearer ")) {
여기도?

2023-08-02 23:40 UTC, cookienc commented on backend/baton/src/main/java/touch/baton/domain/oauth/controller/OauthController.java
> +            HttpServletResponse response
```java
public ResponseEntity<Void> redirectAuthCode(@PathVariable("oauthType")OauthType oauthType,
        HttpServletResponse response
```
요렇게 바꿔주세용 아래도!

2023-08-02 23:40 UTC, cookienc commented on backend/baton/src/main/java/touch/baton/infra/auth/jwt/JwtConfig.java
> +@ConfigurationProperties("jwt.token")
이거 좀 멋있네요👍

2023-08-02 23:40 UTC, cookienc commented on backend/baton/src/main/java/touch/baton/infra/auth/oauth/github/client/GithubInformationClient.java
> +public class GithubInformationClient implements OauthInformationClient {
Oauth관련 인터페이스들은 도메인에 있고, 구현체들은 infra.auth.oauth 패키지에 있는데 무슨 차이인가요? (진짜 모름)

2023-08-03 00:44 UTC, hyena0608 commented on backend/baton/src/main/java/touch/baton/infra/auth/oauth/github/client/GithubInformationClient.java
> +public class GithubInformationClient implements OauthInformationClient {
깃허브 소셜 로그인 기능은 외부에 의존하고 있어서 도메인 패키지 내부에 있는 oauth에 의존성을 끊기 위해서 패키지를 분리했습니다!

2023-08-03 00:44 UTC, hyena0608 commented on backend/baton/src/main/java/touch/baton/infra/auth/jwt/JwtConfig.java
> +@ConfigurationProperties("jwt.token")
😎

2023-08-03 00:50 UTC, hyena0608 commented on backend/baton/src/main/java/touch/baton/domain/oauth/controller/AuthSupporterPrincipalArgumentResolver.java
> +        if (!authHeader.startsWith("Bearer ")) {
수정했습니다!

2023-08-03 01:00 UTC, shb03323 commented on backend/baton/src/main/java/touch/baton/domain/oauth/controller/AuthRunnerPrincipalArgumentResolver.java
> +        }
메소드 분리해도 될 것 같습니다!

2023-08-03 01:01 UTC, shb03323 commented on backend/baton/src/main/java/touch/baton/domain/oauth/controller/AuthRunnerPrincipalArgumentResolver.java
> +        final String email = claims.get("email", String.class);
상수화 해야하나...? 흠

2023-08-03 01:40 UTC, shb03323 commented on backend/baton/src/main/java/touch/baton/domain/oauth/service/OauthService.java
> +    }
save 보다는 회원가입이니깐 signup 이라고 하면 어때?

2023-08-03 01:41 UTC, shb03323 commented on backend/baton/src/main/java/touch/baton/domain/oauth/service/OauthService.java
> +        if (memberMember.isEmpty()) {
```suggestion
        final Optional<Member> searchedMember = oauthMemberRepository.findMemberByOauthId(oauthInformation.getOauthId());
        if (searchedMember.isEmpty()) {
```

2023-08-03 01:49 UTC, shb03323 commented on backend/baton/src/test/java/touch/baton/config/MockMvcTest.java
> +}
공부해보겠습니다.

2023-08-03 01:50 UTC, shb03323 commented on backend/baton/src/test/java/touch/baton/infra/auth/jwt/JwtEncoderAndDecoderTest.java
> +    @DisplayName("Claim 으로 email 을 넣어 인코딩한 JWT 를 디코드했을 때 email 을 구할 수 있다..")
. 두개

2023-08-03 04:07 UTC, hyena0608 commented on backend/baton/src/test/java/touch/baton/infra/auth/jwt/JwtEncoderAndDecoderTest.java
> +    @DisplayName("Claim 으로 email 을 넣어 인코딩한 JWT 를 디코드했을 때 email 을 구할 수 있다..")
수정 완료!

2023-08-03 04:21 UTC, shb03323 approved these changes
LGTM!

2023-08-03 04:24 UTC, cookienc approved these changes
LGTM!

2023-08-03 04:25 UTC, merged