domain exception이 server exception을 상속받도록 수정
woowacourse-teams/2023-baton pull request #177
Opened 2023-08-01 11:56 UTC by eunbii0213

## 관련이슈

- resolved #168 

## 참고사항
domain exception이 server exception을 상속받도록 수정했습니다. 
Member의 테스트코드(null값 검사)도 message 또한 검증하도록 변경했습니다.

2023-08-01 12:08 UTC, shb03323 commented on backend/baton/src/main/java/touch/baton/domain/common/vo/Contents.java
> +            throw new IllegalArgumentException("Contents 객체 내부에 contents 는 null 일 수 없습니다.");
꼼꼼 굿굿

2023-08-01 12:09 UTC, shb03323 commented on backend/baton/src/main/java/touch/baton/domain/common/vo/Contents.java
> +            throw new IllegalArgumentException("Contents 객체 내부에 contents 는 null 일 수 없습니다.");
근데 IllegalArgumentException으로 하기로 했었는지 DomainException으로 하기로 했었는지 기억이 안나네...

2023-08-01 12:09 UTC, shb03323 commented on backend/baton/src/main/java/touch/baton/domain/member/exception/MemberException.java
> +}
주석데스네...?

2023-08-01 12:10 UTC, eunbii0213 commented on backend/baton/src/main/java/touch/baton/domain/member/exception/MemberException.java
> +}
헉 이게뭐야!!!!!!

2023-08-01 12:12 UTC, eunbii0213 commented on backend/baton/src/main/java/touch/baton/domain/member/exception/MemberException.java
> +}
이것저것 실험해본다고 주석 했다가 풀었다가 했었는데 ㅋㅋㅋㅋ 지우는 걸 깜빡했나보군요.. 죄송합니다. 바로 반영했습니다👍

2023-08-01 12:12 UTC, shb03323 commented on backend/baton/src/test/java/touch/baton/domain/member/MemberTest.java
> +                    .hasMessage("Member 의 name 은 null 일 수 없습니다.");
hasMessage를 넣으면 완벽하게 예외를 검증할 수 있지만, 예외 메시지 수정만으로 테스트 코드를 수정해야한다는 번거로움이 있을 것 같아. 트레이드 오프인데 다들 어떻게 생각해?

2023-08-01 12:12 UTC, shb03323 requested changes
주석은 지워주세용

2023-08-01 12:15 UTC, eunbii0213 commented on backend/baton/src/test/java/touch/baton/domain/member/MemberTest.java
> +                    .hasMessage("Member 의 name 은 null 일 수 없습니다.");
맞아. 디투말처럼 확실히 트레이드 오프인 것 같긴 해! 

일단 나는 개인적으로 넣는 걸 선호해! 사실 hasMessage()넣기 전에 test 통과해서 코드 잘 짠 줄 알았는데, 알고보니 message가 Null로 들어왔었던 상황이 벌어졌거든..ㅎㅎ
이런걸 예방할 수 있어서  추가했던 거였어! 다들 어떻게 생각하는지 궁금쓰 🤔

2023-08-01 12:15 UTC, eunbii0213 commented
> 주석은 지워주세용

지웠습니다 디투~~ 호호호 감사합니다

2023-08-01 13:10 UTC, shb03323 approved these changes
LGTM!

2023-08-01 23:14 UTC, cookienc commented on backend/baton/src/main/java/touch/baton/domain/common/vo/Contents.java
> +            throw new IllegalArgumentException("Contents 객체 내부에 contents 는 null 일 수 없습니다.");
VO니까 Illeagl이 맞는듯

2023-08-01 23:18 UTC, cookienc commented on backend/baton/src/test/java/touch/baton/domain/member/MemberTest.java
> +                    .hasMessage("Member 의 name 은 null 일 수 없습니다.");
나는 검증 안하는 편인데 꼼꼼히 할꺼면 검증해도 괜찮을 듯! 예외 메세지를 자주 변경하지는 않을 것 같아서 그렇게 큰 부담이 들지는 않을것 같아. 근데 추가할거면 나중에 테스트 코드 리팩토링할 때 나머지 테스트에서도 메세지를 검증해야될 것 같아

2023-08-01 23:18 UTC, cookienc approved these changes
LGTM!

2023-08-02 00:50 UTC, hyena0608 approved these changes
고생하셨어요

2023-08-02 00:50 UTC, merged