모든 도메인 객체 exception Notnull method 제거
woowacourse-teams/2023-baton pull request #184
Opened 2023-08-02 11:07 UTC by eunbii0213

## 관련이슈

- resolved #180 

## 참고사항
모든 도메인 객체 exception Notnull method 제거했습니다.

2023-08-02 23:51 UTC, cookienc requested changes

2023-08-02 23:51 UTC, cookienc commented on backend/baton/src/main/java/touch/baton/domain/runnerpost/service/RunnerPostService.java
> +        final List<RunnerPostTag> postTags = toSaveTags.stream().map(tag -> RunnerPostTag.builder().tag(tag).runnerPost(runnerPost).build()).toList();
이 클래스에서 stream 관련해서 정렬이 다 바꼈어~

2023-08-03 05:30 UTC, eunbii0213 commented on backend/baton/src/main/java/touch/baton/domain/runnerpost/service/RunnerPostService.java
> +        final List<RunnerPostTag> postTags = toSaveTags.stream().map(tag -> RunnerPostTag.builder().tag(tag).runnerPost(runnerPost).build()).toList();
반영했습니다!!

2023-08-03 05:32 UTC, cookienc submitted a review, later dismissed
LGTM!

2023-08-03 05:51 UTC, hyena0608 reviewed
혹시 몰라서 한 번 확인 부탁드리겠습니다!

2023-08-03 05:51 UTC, hyena0608 commented on backend/baton/src/main/java/touch/baton/domain/technicaltag/TechnicalTag.java
> +            throw new TagDomainException("tagName 은 null 일 수 없습니다.");
저희 Tag가 아닌 TechnicalTagDomainException으로 해야할거 같습니다!

2023-08-03 06:38 UTC, eunbii0213 commented on backend/baton/src/main/java/touch/baton/domain/technicaltag/TechnicalTag.java
> +            throw new TagDomainException("tagName 은 null 일 수 없습니다.");
RunnerPostTag 또한 구체화해서 따로 Exception 빼두었습니다!! 좋은 지적 bbb

2023-08-03 06:54 UTC, 2023baton approved these changes
LGTM!

2023-08-03 06:54 UTC, shb03323 commented on backend/baton/src/main/java/touch/baton/domain/runnerpost/service/RunnerPostService.java
> +                        runnerPost(runnerPost).build())
점 위치가 이상해용

2023-08-03 06:55 UTC, hyena0608 approved these changes

2023-08-03 06:58 UTC, cookienc approved these changes
고생하셨습니다~

2023-08-03 06:59 UTC, hyena0608 approved these changes

2023-08-03 07:05 UTC, merged