웹팩 플러그인 설정 수정
woowacourse-teams/2023-baton pull request #313
Opened 2023-08-10 11:16 UTC by tkdrb12

## 관련이슈

- resolved #307 
## 참고사항
- [ ] EnvironmentPlugin 플러그인이 prod환경에서만 동작하도록 변경

2023-08-10 11:23 UTC, gyeongza requested changes

2023-08-10 11:23 UTC, gyeongza commented on frontend/webpack/webpack.prod.js
> +    }),
dev, prod에 공통적으로 들어가는건 common에 넣어주면 될 것 같아용!

2023-08-11 05:43 UTC, gyeongza approved these changes

2023-08-11 05:43 UTC, guridaek approved these changes

2023-08-11 05:44 UTC, merged