서포터 프로필 변경 API
woowacourse-teams/2023-baton pull request #315
Opened 2023-08-10 13:25 UTC by shb03323

## 관련이슈

- resolved #309 

## 참고사항
- 테스트가 조금 많습니다. (Entity 테스트 조금 더 추가했습니다.)
- `Supporter`와 `Member` 앤티티 부분에 validate 하는 것들 다 메소드 분리 했습니다.
    - 이유는 update 시에 not null 해줘야하기 때문
- 수정할 때 또 `technicalTag`가 문제인데, `SupporterTechnicalTag`를 싹다 지우고 새로운 `SupporterTechnicalTag`를 넣어주었습니다.
    - 바뀌지 않는 것은 삭제하지 않고, 바뀌는 것만 삭제하거나 추가하려 했는데 이렇게 하면 쿼리 수가 더 많아지더라구요.
    - 코드도 더러워지더라구요.
    - 단점은 있습니다. 새로운 데이터를 넣는 것이기 때문에 id가 기존에 비해 빠르게 커질 우려가 있습니다.
- 이벤트 배우고 싶네요. SupporterProfile 서비스에서 기술 태그 관련 레포를 불러오니깐 의존이 많아지는 듯한 느낌이에요.

2023-08-10 15:19 UTC, hyena0608 commented on backend/baton/src/main/java/touch/baton/domain/member/Member.java
> +    private static void validateImageUrlNotNull(final ImageUrl imageUrl) {
static 자동완성 됐어요!

2023-08-10 15:19 UTC, hyena0608 commented on backend/baton/src/main/java/touch/baton/domain/supporter/Supporter.java
> +    private static void validateSupporterTechnicalTagsNotNull(final SupporterTechnicalTags supporterTechnicalTags) {
static!

2023-08-10 15:19 UTC, hyena0608 commented on backend/baton/src/main/java/touch/baton/domain/member/Member.java
> +    }
저희가 수정할 때 모든 값을 프론트에서 다 받는데
그러면 update 메서드를 하나하나 만들지 않고 updateMember 를 받는거는 어떤가요?

```suggestion
   public void updateMember(final Member updateMember) {
       this.memberName = updateMember.getMemberName();
       // ...
   }
```

2023-08-10 15:19 UTC, hyena0608 commented on backend/baton/src/main/java/touch/baton/domain/supporter/Supporter.java
> +    }
서포터가 연관관계 주인으로 사용자의 이름이나 회사 정보를 수정할 수 있는 거는 맞지만
Member는 Member 객체를 통해서 update하게 하는거는 어떨까요?

Supporter가 Member를 수정하는 메서드를 만들고
Runner도 마찬가지로 Member를 수정하는 메서드를 만들면

여러 곳에서 Member를 수정할 수 있기 때문에 변경에 대해 신경을 써야할 부분이 늘어나는거 같다고 느낍니다.

2023-08-10 15:19 UTC, hyena0608 commented on backend/baton/src/main/java/touch/baton/domain/supporter/service/SupporterService.java
> +        supporter.updateSupporterTechnicalTags(supporterTechnicalTags);
서포터 기술 태그를 생성해서 영속화 시켰는데
서포터에 다시 update 메서드를 호출해서 넣는 이유가 궁금합니다

2023-08-10 15:19 UTC, hyena0608 commented on backend/baton/src/main/java/touch/baton/domain/technicaltag/SupporterTechnicalTags.java
> +    }
기존 서포터 기술 태그 목록이 지워지고
내부 값은 같지만 새로운 인스턴스인 서포터 기술 태그 목록이 들어오면 위험할 수도 있을거 같습니다.
외부 service 계층에서 서포터 기술 태그 목록을 주입할 때 기존 영속화되어야만 괜찮을거 같다고 느낍니다.

2023-08-10 15:19 UTC, hyena0608 commented on backend/baton/src/test/java/touch/baton/assure/supporter/SupporterProfileAssuredUpdateTest.java
> +public class SupporterProfileAssuredUpdateTest extends AssuredTestConfig {
👍

2023-08-11 04:16 UTC, cookienc requested changes
굿굿

2023-08-11 04:16 UTC, cookienc commented on backend/baton/src/test/java/touch/baton/document/profile/supporter/update/SupporterProfileUpdateApiTest.java
> +                .andExpect(header().string("Location", "/api/v1/profile/supporter/me"))
As-Is
> > "Location"

To-Be
> HttpHeaders.LOCATION

어떠신가요

2023-08-11 04:47 UTC, shb03323 commented
1. ErrorResponse record로 변경했습니다.
2. 삭제 시에 batch delete 적용했습니다.

2023-08-11 05:08 UTC, hyena0608 submitted a review, later dismissed
테스트 좋네요!

2023-08-11 05:09 UTC, eunbii0213 commented on backend/baton/src/test/java/touch/baton/domain/supporter/service/SupporterServiceTest.java
>      @DisplayName("Supporter 식별자 값으로 Member 패치 조인하여 Supporte 를 조회한다.")
여기 오타있습니다!

2023-08-11 05:28 UTC, cookienc approved these changes
LGTM!

2023-08-11 05:29 UTC, eunbii0213 approved these changes
GOOD!! 짱짱 개발자!

2023-08-11 05:29 UTC, hyena0608 approved these changes
굿굿

2023-08-11 05:29 UTC, merged