Runner profile 수정 API 구현
woowacourse-teams/2023-baton pull request #325
Opened 2023-08-11 06:45 UTC by eunbii0213

## 관련이슈

- resolved #320 

## 참고사항

2023-08-11 06:52 UTC, shb03323 commented on backend/baton/src/main/java/touch/baton/domain/common/exception/ClientErrorCode.java
> +    RUNNER_PROFILE_INTRODUCTION_IS_NULL(HttpStatus.BAD_REQUEST, "RNP002", "러너의 자기소개를 입력해주세요.");
RNP002 는 지워도 될 것 같습니다. nullable이라.

RNP001은 MB001로 대체하시면 좋을 것 같아요.

2023-08-11 06:54 UTC, shb03323 commented on backend/baton/src/main/java/touch/baton/domain/member/Member.java
> +@Setter
세터는 금지입니다. 세터를 열게 되면 모든 필드에 대해 변경할 수 있기 때문에 위험해서요.
직접 메소드를 정의해서 update~~ 형태로 바꿔주시면 좋을 것 같아요.

2023-08-11 06:54 UTC, hyena0608 requested changes

2023-08-11 06:54 UTC, hyena0608 commented on backend/baton/src/main/java/touch/baton/domain/member/Member.java
> +@Setter
@Setter 하신 이유가 있으신가요?

2023-08-11 06:54 UTC, hyena0608 commented on backend/baton/src/main/java/touch/baton/domain/runner/Runner.java
> +@Setter
위와 같은 내용입니다!

2023-08-11 06:54 UTC, hyena0608 commented on backend/baton/src/main/java/touch/baton/domain/runner/controller/RunnerProfileController.java
> +    @ResponseStatus(HttpStatus.NO_CONTENT)
ResponseEntity로 뺄 수 있을거 같네요!

2023-08-11 06:54 UTC, hyena0608 commented on backend/baton/src/main/java/touch/baton/domain/runner/service/RunnerProfileRequest.java
> +) {
컨벤션 부탁드립니다!

2023-08-11 06:54 UTC, hyena0608 commented on backend/baton/src/main/java/touch/baton/domain/runner/service/RunnerProfileService.java
> +@Transactional
이거는 서비스를 Update 전용으로 할지 팀에서 정해보면 좋을거 같아요!

2023-08-11 06:54 UTC, hyena0608 commented on backend/baton/src/main/java/touch/baton/domain/runner/service/RunnerProfileService.java
> +                })
람다 내부에 너무 많은 내용이 들어가면 가독성이 좋은거 같지 않습니다.

2023-08-11 06:54 UTC, hyena0608 commented on backend/baton/src/main/java/touch/baton/domain/runner/service/RunnerProfileService.java
> +                .collect(Collectors.toList());
toList()

2023-08-11 06:54 UTC, hyena0608 commented on backend/baton/src/main/java/touch/baton/domain/technicaltag/RunnerTechnicalTags.java
> +    public void clear(){
띄어쓰기가 필요할거 같아요! 또한 너무 위험한 메서드라고 느껴집니다.

2023-08-11 06:54 UTC, hyena0608 commented on backend/baton/src/main/java/touch/baton/domain/runner/service/RunnerProfileRequest.java
> +        String[] technicalTags
배열을 쓰신 이유가 있으신가요?

2023-08-11 06:55 UTC, shb03323 commented on backend/baton/src/main/java/touch/baton/domain/runner/Runner.java
> +@Setter
요기도 마찬가지로 세터 지워주십쇼.

2023-08-11 06:55 UTC, hyena0608 commented on backend/baton/src/main/java/touch/baton/domain/runner/service/RunnerProfileRequest.java
> +public record RunnerProfileRequest(
Update인지 Create인지 무엇을 위한 Request인지 잘 모르겠어요!

2023-08-11 06:56 UTC, shb03323 commented on backend/baton/src/main/java/touch/baton/domain/runner/controller/RunnerProfileController.java
> +    }
1. 어노테이션으로 `@ResponseStatus`를 정의하는 것은 저희 컨벤션과 맞지 않습니다. 직접 ResponseEntity.noContent() 형태로 해주세요.
2. Location이 없습니다. Location 넣어주십쇼.
3. RequestBody에 `@Valid`가 빠졌습니다. 예외 처리가 되지 않았을텐데 직접 확인해보셨나요...?

2023-08-11 06:58 UTC, shb03323 commented on backend/baton/src/main/java/touch/baton/domain/runner/service/RunnerProfileRequest.java
> +        @ValidNotNull(clientErrorCode = ClientErrorCode.RUNNER_PROFILE_INTRODUCTION_IS_NULL)
1. 소개는 nullable합니다.
2. 소속은 not null 입니다.

2023-08-11 06:58 UTC, shb03323 commented on backend/baton/src/main/java/touch/baton/domain/runner/service/RunnerProfileRequest.java
> +        String[] technicalTags
List가 아닌 Array를 쓰신 이유에 대해 여쭈어봐도 될까요?

2023-08-11 07:00 UTC, shb03323 commented on backend/baton/src/main/java/touch/baton/domain/runner/service/RunnerProfileService.java
> +}
RunnerService가 따로 있는데 RunnerProfileService를 새로 만드신 이유에 대해 여쭈어봐도 될까요?

2023-08-11 07:00 UTC, shb03323 commented on backend/baton/src/main/java/touch/baton/domain/runner/service/RunnerProfileService.java
> +}
메소드 인자에 final 빼먹으셨습니다.

2023-08-11 07:01 UTC, cookienc commented on backend/baton/src/main/java/touch/baton/domain/runner/service/RunnerProfileService.java
> +@Transactional
클래스에 `@Transactional(readonly=true)` 붙이는게 컨벤션입니다!
`@Transtional`이 필요하면 메서드에서 붙여주세요

2023-08-11 07:02 UTC, cookienc commented on backend/baton/src/main/java/touch/baton/domain/runner/service/RunnerProfileService.java
> +                .collect(Collectors.toList());
한 메서드에서 두 가지 일(teachnicalTag를 만들고 저장 + RunerTechnicalTag를 만들고 저장)을 하는데요. 메서드를 분리해보는건 어떨까요? 
+ 지역변수에 final이 빠졌어요

2023-08-11 07:03 UTC, cookienc commented on backend/baton/src/main/java/touch/baton/domain/runner/Runner.java
> +@Setter
위와 동일합니다

2023-08-11 07:04 UTC, shb03323 commented on backend/baton/src/main/java/touch/baton/domain/runner/service/RunnerProfileService.java
> +}
만약 저장하려는 TechnicalTag가 데이터베이스에 존재하면 어떻게 될까요? tagname이 unique라서 데이터베이스 오류가 발생하지 않을까요?
또 만약 해당 API를 두 번 호출하면 어떻게 될까요? 기존의 runnerTechnicalTag는 지워지지 않고 계속 남지 않나요?

2023-08-11 07:05 UTC, cookienc commented on backend/baton/src/test/java/touch/baton/document/profile/runner/read/RunnerProfileReadApiTest.java
> +    RunnerProfileService runnerProfileService;
접근제한자가 없습니당

2023-08-11 07:06 UTC, cookienc commented on backend/baton/src/test/java/touch/baton/document/profile/runner/read/RunnerProfileReadApiTest.java
> +//    }
요건 디투가 작성한건데 안쓰는거여서 지우는거 허락받았습니다

2023-08-11 07:07 UTC, shb03323 commented on backend/baton/src/main/java/touch/baton/domain/runner/service/RunnerProfileService.java
> +}
runnerTechnicalTag를 저장하고나서 RunnerTechnicalTags.update 메소드를 실행하면 어떻게 되나요? 데이터가 정상적으로 저장이 되었나요?

2023-08-11 07:08 UTC, shb03323 commented on backend/baton/src/main/java/touch/baton/domain/runner/service/RunnerProfileService.java
> +        runner.getMember().setCompany(new Company(runnerProfileRequest.company()));
getter.setter 를 사용하는게 객체지향적으로 보이지 않습니다. 응집력이 떨어져요.

2023-08-11 07:08 UTC, shb03323 commented on backend/baton/src/main/java/touch/baton/domain/runner/service/RunnerProfileService.java
> +        runner.getMember().setCompany(new Company(runnerProfileRequest.company()));
저희가 만든 getter는 어떤 용도로 만들었는지 생각해보시면 좋을 것 같아요.

2023-08-11 07:09 UTC, cookienc commented on backend/baton/src/test/java/touch/baton/domain/runner/service/RunnerProfileServiceTest.java
> +                () -> assertThat(runnerJudy.getRunnerTechnicalTags().getRunnerTechnicalTags().get(1).getTechnicalTag().getTagName().getValue()).isEqualTo("changedTag2")
스트림을 써서`containsExactly()`를 써보는건 어떨까요?

2023-08-11 07:09 UTC, shb03323 commented on backend/baton/src/main/java/touch/baton/domain/technicaltag/RunnerTechnicalTags.java
> +    }
외부에서 clear가 쓰이나요? private로 하면 어떨까요?
또, 내부에서만 사용되는 것이라면 해당 메소드를 지우고 update 메소드에 `this.runnerTechnicalTags.clear()` 를 하면 어떨까요?

2023-08-11 07:11 UTC, shb03323 commented on backend/baton/src/test/java/touch/baton/config/ServiceTestConfig.java
> +
지금 파일을 보았을 때 runner -> supporter 순서로 변수들이 배치가 되어있는데,
technicalTagRepository 와 supporterTechnicalTagRepository 사이에 위치시키시는 것은 어떤가요?

2023-08-11 07:15 UTC, shb03323 commented on backend/baton/src/test/java/touch/baton/domain/runner/service/RunnerProfileServiceTest.java
> +    }
이 테스트는 updateRunnerProfile() 을 실행하지 않아도 통과하는 테스트로 보입니다.

2023-08-11 07:22 UTC, shb03323 requested changes
restdocs 테스트와 restassured 테스트가 없습니다ㅠㅠㅠ

혹시 postman으로 직접 돌려보셨나요? 꼼꼼하게 체크하면 좋을 것 같아서요:)

2023-08-11 17:13 UTC, shb03323 commented on backend/baton/src/main/java/touch/baton/domain/runner/Runner.java
> +    }
null validation을 여기서도 하면 어떨까요? 여긴 서버딴 validation이요!

2023-08-11 17:14 UTC, shb03323 commented on backend/baton/src/main/java/touch/baton/domain/runner/controller/RunnerProfileController.java
> +    }
와우 굿굿

2023-08-11 17:18 UTC, eunbii0213 commented on backend/baton/src/main/java/touch/baton/domain/runner/Runner.java
> +    }
어라! introduction은 nullable아닌가요?!

2023-08-11 17:19 UTC, eunbii0213 commented on backend/baton/src/main/java/touch/baton/domain/runner/Runner.java
> +    }
member의 memberName이나 company같은 걸 말씀하시는거죠?!

2023-08-11 17:20 UTC, shb03323 commented on backend/baton/src/main/java/touch/baton/domain/runner/service/RunnerService.java
> +    }
사실살 tagName들만 필요한 것인데 request 전체를 보내고 있어요. tagName 목록만 보내는 것은 어떨까요?

2023-08-11 17:24 UTC, eunbii0213 commented on backend/baton/src/main/java/touch/baton/domain/runner/service/RunnerService.java
> +    }
오!! 정말 그렇네요! request 모두 보내는 건 불필요하네요! 바로 변경했슴다~ ㅎㅎ

2023-08-11 17:26 UTC, shb03323 requested changes
와 짧은 시간에 되게 빠르게 바뀌었어요!! 
저녁은 드셨나요... 와...

조금의 코멘트 있는데 확인해주시면 감사하겠습니다.

2023-08-11 22:42 UTC, hyena0608 commented on backend/baton/src/main/java/touch/baton/domain/runner/service/RunnerProfileService.java
> +                .collect(Collectors.toList());
리팩터링 부탁드립니다.

2023-08-11 22:42 UTC, hyena0608 commented on backend/baton/src/main/java/touch/baton/domain/runner/service/RunnerProfileService.java
> +        runner.getRunnerTechnicalTags().update(convertToRunnerTechnicalTags(runner, runnerProfileRequest));
리팩터링 부탁드립니다.

2023-08-11 22:42 UTC, hyena0608 commented on backend/baton/src/main/java/touch/baton/domain/technicaltag/RunnerTechnicalTags.java
> +    }
위험한 메서드 처리 부탁드립니다.

2023-08-11 22:42 UTC, hyena0608 commented on backend/baton/src/main/java/touch/baton/domain/runner/service/RunnerProfileRequest.java
> +        String[] technicalTags
배열 쓰신 이유 궁금합니다~

2023-08-11 22:51 UTC, hyena0608 commented on backend/baton/src/main/java/touch/baton/domain/runner/service/RunnerService.java
> +    }
메서드명 컨벤션 있습니다.

2023-08-11 22:51 UTC, hyena0608 commented on backend/baton/src/main/java/touch/baton/domain/runner/service/RunnerService.java
> +        return runnerTechnicalTag;
```suggestion
        return runnerTechnicalTagRepository.save(runnerTechnicalTag);
```

2023-08-11 22:51 UTC, hyena0608 commented on backend/baton/src/test/java/touch/baton/assure/runner/RunnerProfileAssuredSupport.java
> +        }
프로필 수정에 대한 검증을 추가하시는거는 어떤가요?

2023-08-11 22:51 UTC, hyena0608 commented on backend/baton/src/test/java/touch/baton/domain/runner/service/RunnerProfileServiceTest.java
> +                .doesNotThrowAnyException();
수정된 값을 조회해서 검증하는거는 어떤가요?

2023-08-11 22:51 UTC, hyena0608 commented on backend/baton/src/test/java/touch/baton/assure/runner/RunnerProfileAssuredUpdateTest.java
> +        final RunnerUpdateRequest runnerUpdateRequest = new RunnerUpdateRequest("업데이트된 이름", "업데이트된 소속", "업데이트된 자기소개", List.of("업데이트 태그1", "업데이트 태그2"));
변수명을 한글로 쓰는 거는 어떤가요?

2023-08-11 22:51 UTC, hyena0608 commented on backend/baton/src/test/java/touch/baton/assure/runner/RunnerProfileAssuredSupport.java
> +        public RunnerProfileClientRequestBuilder 러너_본인_프로필을_수정한다(final RunnerUpdateRequest request) {
HTTP_STATUS 이외 메서드의 파라미터명을 한글로 쓰는거는 어떤가요

2023-08-11 22:51 UTC, hyena0608 commented on backend/baton/src/main/java/touch/baton/domain/runner/controller/RunnerProfileController.java
> +                                                @RequestBody @Valid final RunnerUpdateRequest runnerUpdateRequest){
컨벤션 부탁드립니다.

2023-08-12 03:24 UTC, cookienc submitted a review, later dismissed
밤 늦게까지 고생하네요👍
(approve 잘 못 누름)

2023-08-12 03:24 UTC, cookienc commented on backend/baton/src/test/java/touch/baton/assure/runner/RunnerProfileAssuredUpdateTest.java
> +        final Member 사용자_주디 = memberRepository.save(MemberFixture.createWithSocialId(주디_소셜_id));
이렇게 쓰면 createWithSocialId에 memberName은 디투인데 Member 변수명이 사용자_주디라 헷갈릴거 같네요

2023-08-12 05:45 UTC, shb03323 commented on backend/baton/src/main/java/touch/baton/domain/runner/Runner.java
> +    }
기본값으로 해야할듯...ㅠ

2023-08-12 05:45 UTC, shb03323 commented on backend/baton/src/main/java/touch/baton/domain/runner/controller/RunnerProfileController.java
> +                                                @RequestBody @Valid final RunnerUpdateRequest runnerUpdateRequest){
띄어쓰기!

2023-08-12 05:46 UTC, shb03323 commented on backend/baton/src/main/java/touch/baton/domain/runner/service/RunnerService.java
> +        );
```suggestion
        return technicalTagRepository.findByTagName(tagName).orElseGet(
                () -> technicalTagRepository.save(TechnicalTag.builder()
                        .tagName(tagName)
                        .build())
        );
```

2023-08-12 05:47 UTC, shb03323 commented on backend/baton/src/main/java/touch/baton/domain/runner/service/dto/RunnerUpdateRequest.java
> +                                  List<String> technicalTags) {
컨벤션!

2023-08-12 05:48 UTC, shb03323 commented on backend/baton/src/test/java/touch/baton/assure/runner/RunnerProfileAssuredSupport.java
> +        }
이건 저도 적용하지 못했는데 해야겠군요.

2023-08-12 05:49 UTC, shb03323 commented on backend/baton/src/test/java/touch/baton/domain/runner/service/RunnerProfileServiceTest.java
> +                .doesNotThrowAnyException();
저도 그렇게 처리하겠습니다.

2023-08-12 05:50 UTC, shb03323 requested changes
확인 부탁드립니다!

2023-08-12 06:34 UTC, eunbii0213 commented on backend/baton/src/test/java/touch/baton/assure/runner/RunnerProfileAssuredSupport.java
> +        }
컨트롤러에서 작성하면 테스트 돌리는데 시간 너무 오래 걸릴 것 같아서 서비스 단위 테스트로 작성했습니다!

2023-08-12 06:40 UTC, eunbii0213 commented on backend/baton/src/main/java/touch/baton/domain/runner/service/dto/RunnerUpdateRequest.java
> +                                  List<String> technicalTags) {
이 부분 어떤 면에서 컨벤션에 어긋난건가요?? SupporterUpdateRequest랑 비교해도 잘 모르겠네요 ㅜ

2023-08-12 15:02 UTC, hyena0608 reviewed
💪

2023-08-12 15:02 UTC, hyena0608 commented on backend/baton/src/test/java/touch/baton/domain/runner/service/RunnerServiceUpdateTest.java
> +        assertAll(
```suggestion
        // when
        runnerService.updateRunner(runnerJudy, runnerUpdateRequest);
        final Optional<Runner> maybeRunnerJudy = runnerRepository.findById(runnerJudy.getId());
        final RunnerResponse.MyProfile judyRunnerProfile = RunnerResponse.MyProfile.from(foundJudy.get());

        // then
        assertAll(
```

2023-08-12 15:02 UTC, hyena0608 commented on backend/baton/src/test/java/touch/baton/domain/runner/service/RunnerServiceUpdateTest.java
> +        final RunnerResponse.MyProfile judyProfile = RunnerResponse.MyProfile.from(foundJudy.get());
서비스에서는 응답 객체에 대해 모르는 편이 좋을거 같습니다. (팀 컨벤)

2023-08-13 04:22 UTC, eunbii0213 commented on backend/baton/src/main/java/touch/baton/domain/common/vo/Introduction.java
> +    @ColumnDefault(DEFAULT_VALUE)
@ColumnDefault("안녕하세요")만 넣으면 
DDL 날릴 때 

`create table runner (
        created_at timestamp(6) not null,
        deleted_at timestamp(6),
        id bigint generated by default as identity,
        member_id bigint not null unique,
        updated_at timestamp(6) not null,
        introduction varchar(255) default 안녕하세요.,
        primary key (id)
    )`
    
    이렇게 날아가서 오류 발생해요! 숫자는 상관없는데 문자열은 ''로 묶어줘야 하잖아요! 그래서 @ColumnDefault("'안녕하세요.'")로 작성되어야 정상적으로 DDL이 날아가서 "'안녕하세요'"로 설정했던 거였습니다 ㅎㅅㅎ.

2023-08-13 04:26 UTC, eunbii0213 commented on backend/baton/src/main/java/touch/baton/domain/common/vo/Introduction.java
> +        return value;
저는 Introduction은 null 을 허용해줬으니 괜찮다고 생각했습니다! 헤나는 어떻게 생각하시나요??

2023-08-13 04:29 UTC, eunbii0213 commented on backend/baton/src/main/java/touch/baton/domain/runner/Runner.java
> +    }
앗 이 부분은 제가 놓쳤네요. 수정하겠습니다!

2023-08-13 04:39 UTC, eunbii0213 commented on backend/baton/src/main/java/touch/baton/domain/runner/Runner.java
> +    }
처음엔 
- 제가 제안 드렸던 yaml에 속성을 추가하는 방식으로 코드가 작성
- 해당 방식은 Introduction의 value에 Null이 들어올 수 있음 (new Introduction(null))
- Introduction의 주소값 변경 없이 값만 바꿔주면 좋지 않을까?
란 생각에 작성했던 코드입니다. 다른 update 메서드랑은 케이스가 다르다고 생각했던 것 같아요. (내부 값 검증은 Runner가 아닌 Introduction의 역할이라고 생각하기도 했어요.)

그런데 리뷰를 보고 다시 생각해보니 논의 후 yaml에 속성을 추가하지도 않게 됐을 뿐더러 팀원들의 코드 스타일과는 다르게 보이기도 하네요! 수정해보겠습니다!

2023-08-13 04:43 UTC, eunbii0213 commented on backend/baton/src/main/java/touch/baton/domain/runner/Runner.java
> +    }
그렇지만 Runner에게 뺀다고 했을 때, Introduction의 내부 값을 null 체크를 한 번 하고 "안녕하세요"로 바꿔야하는데 이게 Runner가 알아야 할 정보인지 모르겠어요.

DefaultValue로 설정해준 "안녕하세요"도 어떻게 빼서 Runner에서 쓸 수 있을지 잘 모르겠구요..어떻게 생각하시나요??

2023-08-13 04:52 UTC, eunbii0213 commented on backend/baton/src/main/java/touch/baton/domain/runner/Runner.java
> +    }
그런데 Supporter, Runner에게 빼니 중복되는 코드가 생기는 느낌이에요. 이 부분은 어떻게 생각하시나요??

2023-08-13 07:28 UTC, shb03323 commented on backend/baton/src/main/java/touch/baton/domain/common/vo/Introduction.java
> +    }
상수화 나이스

2023-08-13 07:33 UTC, shb03323 commented on backend/baton/src/main/java/touch/baton/domain/runner/Runner.java
> +    }
업데이트는 그대로 Null check하면 좋을 것 같아요!
생성할때만 default로 넣으면 되지 않을까요?

2023-08-13 07:34 UTC, shb03323 commented on backend/baton/src/main/java/touch/baton/domain/runner/controller/RunnerProfileController.java
> +    }
```suggestion
    @PatchMapping("/me")
    public ResponseEntity<Void> updateMyProfile(@AuthRunnerPrincipal final Runner runner,
                                                @RequestBody @Valid final RunnerUpdateRequest runnerUpdateRequest
) {
        runnerService.updateRunner(runner, runnerUpdateRequest);
        final URI redirectUri = UriComponentsBuilder.fromPath("/api/v1/profile/runner/me").build().toUri();
        return ResponseEntity.noContent().location(redirectUri).build();
    }
```

2023-08-13 07:35 UTC, shb03323 commented on backend/baton/src/test/java/touch/baton/assure/runner/RunnerProfileAssuredSupport.java
> +        public void 러너_본인_프로필_수정_성공을_검증한다(final HttpStatus HTTP_STATUS, final Long 러너_아이디) {
아이디 보다는 식별자값으로 하는게 저희 컨벤션입니당

2023-08-13 07:35 UTC, shb03323 approved these changes
LGTM!!

2023-08-13 11:54 UTC, merged