지원한 서포터 목록 조회 API 구현
woowacourse-teams/2023-baton pull request #335
Opened 2023-08-12 17:11 UTC by eunbii0213

## 관련이슈

- resolved #334 

## 참고사항
지원한 서포터 목록 조회 API 구현입니다.

2023-08-13 07:39 UTC, shb03323 commented on backend/baton/src/main/java/touch/baton/domain/runnerpost/controller/response/SupporterRunnerPostResponse.java
> +        }
All 이라는 단어보다는 다른 곳에는 Detail 이라고 나와있는데, Detail로 쓰면 어떨까요?
All 로 쓰게 되면 모든 필드 전체라고 생각할 것 같아요. (id, supporter id, runnerpost id, message 만 있는 것 같았어요.)

2023-08-13 07:40 UTC, shb03323 commented on backend/baton/src/main/java/touch/baton/domain/runnerpost/service/RunnerPostService.java
> +    }
지원한 서포터 목록은 게시글 작성자만 볼 수 있어야 할 것 같아요.

2023-08-13 07:41 UTC, shb03323 requested changes
화이팅!

2023-08-13 12:34 UTC, hyena0608 commented on backend/baton/src/test/java/touch/baton/assure/runnerpost/RunnerPostAssuredSupport.java
> +                });
for문 쓰지 않고도 다른 방식으로 테스트할 수 있을거 같아요!

2023-08-13 12:34 UTC, hyena0608 commented on backend/baton/src/test/java/touch/baton/document/runnerpost/read/RunnerPostReadApiTest.java
> +                );
PathVariable 정보 추가 부탁드려요!

2023-08-14 05:16 UTC, cookienc requested changes
굳굳👍👍

2023-08-14 05:16 UTC, cookienc commented on backend/baton/src/main/java/touch/baton/domain/runnerpost/controller/RunnerPostController.java
> +                                                                    @PathVariable final Long runnerPostId) {
줄바꿈 해주세요!

2023-08-14 05:16 UTC, cookienc commented on backend/baton/src/test/java/touch/baton/document/runnerpost/read/RunnerPostReadApiTest.java
> +        oauthRunnerRepository.save(runner);
oauthRepository 보단 runnerRepository랑 memberRepository를 사용하는게 어떨까요? oauth는 로그인 용으로 사용해서 조회 메서드만 사용하는게 더 적절해 보입니다

2023-08-14 07:33 UTC, shb03323 commented on backend/baton/src/main/java/touch/baton/domain/runner/Runner.java
> +            return new Introduction(Introduction.getDefaultValue());
그냥 return Introduction.getDefaultValue()는 안되나요?

2023-08-14 07:35 UTC, shb03323 commented on backend/baton/src/main/java/touch/baton/domain/runnerpost/service/RunnerPostService.java
> +                filter(supporterRunnerPost -> supporterRunnerPost.getRunnerPost().getRunner().getId() != runnerId)
점(.) 위치 확인해주세용

2023-08-14 07:37 UTC, shb03323 commented on backend/baton/src/main/java/touch/baton/domain/runnerpost/service/RunnerPostService.java
> +                filter(supporterRunnerPost -> supporterRunnerPost.getRunnerPost().getRunner().getId() != runnerId)
runner를 가져와서 runner가 맞는지 확인하는 것은 객체지향적이지 못하다고 생각해용

2023-08-14 07:47 UTC, shb03323 commented on backend/baton/src/main/java/touch/baton/domain/runnerpost/service/RunnerPostService.java
> +                });
흠 해당 stream이 어떤 작업을 하는지 한 눈에 알아보기 힘들었어요ㅠㅠ
filter로 걸렀을 때 존재하면 throw하는 것이 더 좋지 않을까용?

2023-08-14 07:54 UTC, shb03323 commented on backend/baton/src/main/java/touch/baton/domain/runnerpost/service/RunnerPostService.java
> +                });
이 메소드의 동작 순서를 아래와 같이 하면 좋을 것 같은데 어떻게 생각하세요?
1. runnerPostId 로 RunnerPost 를 조회한다.
2. 찾은 runnerPost 의 주인이 runner 가 맞는지 확인한다. 주인이 아니면 예외 처리한다.
3. runnerPostId 로 SupporterRunnerPost 목록을 조회하여 반환한다.

2023-08-14 07:54 UTC, shb03323 commented on backend/baton/src/main/java/touch/baton/domain/supporter/Supporter.java
> +            return new Introduction(Introduction.getDefaultValue());
아까 언급했었슴돠

2023-08-14 07:55 UTC, shb03323 commented on backend/baton/src/main/java/touch/baton/domain/supporter/repository/SupporterRunnerPostRepository.java
> +
readByRunnerPostId로 해도 될 것 같아용

2023-08-14 08:01 UTC, shb03323 commented on backend/baton/src/test/java/touch/baton/assure/runnerpost/RunnerPostReadWithLoginedAssuredTest.java
> +                        ))
이것들을 Support 내부로 넣으면 어때요?

2023-08-14 08:02 UTC, shb03323 commented on backend/baton/src/test/java/touch/baton/assure/runnerpost/RunnerPostReadWithLoginedAssuredTest.java
> +                        ))
response를 위에서 만들어서요

2023-08-14 08:03 UTC, shb03323 commented on backend/baton/src/test/java/touch/baton/document/runnerpost/read/RunnerPostReadApiTest.java
> +        runnerRepository.save(runner);
```suggestion
        final Member member = memberRepository.save(MemberFixture.createHyena());
        final Runner runner = runnerRepository.save(RunnerFixture.createRunner(member));
```

2023-08-14 08:03 UTC, shb03323 commented on backend/baton/src/test/java/touch/baton/document/runnerpost/read/RunnerPostReadApiTest.java
> +        runnerRepository.save(runner);
이런느낌으로 전체적으로 바꾸면 어때요?

2023-08-14 08:04 UTC, shb03323 requested changes
아자아자아자

2023-08-14 08:10 UTC, hyena0608 commented on backend/baton/src/main/java/touch/baton/domain/runnerpost/controller/response/SupporterRunnerPostResponses.java
> +    public record All(List<SupporterRunnerPostResponse.Detail> data) {
All 말고 다른 레코드명은 은 없을까요?

2023-08-14 08:10 UTC, hyena0608 commented on backend/baton/src/main/java/touch/baton/domain/runnerpost/service/RunnerPostService.java
> +                });
검증부 리팩터링 부탁드립니다

2023-08-14 08:10 UTC, hyena0608 commented on backend/baton/src/main/java/touch/baton/domain/supporter/controller/response/SupporterResponse.java
> +
저도 똑같이 생각합니다.

2023-08-14 08:10 UTC, hyena0608 commented on backend/baton/src/main/java/touch/baton/domain/tag/Tag.java
> +
메서드 순서 바뀐거 같네요

2023-08-14 08:10 UTC, hyena0608 commented on backend/baton/src/test/java/touch/baton/assure/runnerpost/RunnerPostAssuredSupport.java
> +
인자랑 응답이랑 타입을 다르게한 다른 이유가 궁금합니다

2023-08-14 08:10 UTC, hyena0608 commented on backend/baton/src/test/java/touch/baton/document/profile/supporter/read/SupporterProfileReadApiTest.java
> +
:(

2023-08-14 08:10 UTC, hyena0608 commented on backend/baton/src/test/java/touch/baton/document/runnerpost/read/RunnerPostReadApiTest.java
> +        runnerRepository.save(runner);
@MockBean 이 어떤 식으로 쓰인건지 궁금합니다

2023-08-14 09:32 UTC, eunbii0213 commented on backend/baton/src/main/java/touch/baton/domain/supporter/controller/response/SupporterResponse.java
> +
오잉 conflict 해결하는 과정에서 위로 올라갔네요.. ㅎㅎ 수정하겠습니다

2023-08-14 09:39 UTC, eunbii0213 commented on backend/baton/src/test/java/touch/baton/assure/runnerpost/RunnerPostReadWithLoginedAssuredTest.java
> +                        ))
고쳐봤는데 제가 맞게 이해한건지 모르겠네요.. 한 번 확인 부탁드립니다!

2023-08-14 09:40 UTC, eunbii0213 commented on backend/baton/src/test/java/touch/baton/document/runnerpost/read/RunnerPostReadApiTest.java
> +        runnerRepository.save(runner);
오 좋은데요?!

2023-08-14 09:42 UTC, eunbii0213 commented on backend/baton/src/test/java/touch/baton/document/runnerpost/read/RunnerPostReadApiTest.java
> +        runnerRepository.save(runner);
일단 급하니까 이것만 바꾸고 나머지 부분은 따로 이슈파서 해도 좋을 것 같아요

2023-08-14 09:52 UTC, eunbii0213 commented on backend/baton/src/main/java/touch/baton/domain/runner/Runner.java
> +            return new Introduction(Introduction.getDefaultValue());
아닙니당 ㅎㅎㅎ 수정하겠습니다!!

2023-08-14 09:52 UTC, eunbii0213 commented on backend/baton/src/main/java/touch/baton/domain/runnerpost/controller/response/RunnerPostResponse.java
> +
그러니까요~! conflict해결하는 과정에서 실수했나봐요 죄송합니다 ㅜ

2023-08-14 09:59 UTC, eunbii0213 commented on backend/baton/src/test/java/touch/baton/assure/runnerpost/RunnerPostAssuredSupport.java
> +
잘 이해가 되지 않았습니다..ㅜ 어떤 인자와 어떤 응답을 말씀하시는 걸까요..? 조금 더 상세하게 얘기해주실 수 있을까요??

2023-08-14 09:59 UTC, eunbii0213 commented on backend/baton/src/test/java/touch/baton/document/profile/supporter/read/SupporterProfileReadApiTest.java
> +
OMG...!

2023-08-14 10:01 UTC, eunbii0213 commented on backend/baton/src/test/java/touch/baton/document/runnerpost/read/RunnerPostReadApiTest.java
> +        runnerRepository.save(runner);
저장해야 인증이 된다고 착각했습니다 ..ㅎㅎ 저장하니 성공한다고 생각했었는데 지워도 성공하더라구요..!! 다른 문제에서 실패했던 거였나봐요^^ㅠ

2023-08-14 10:23 UTC, hyena0608 commented on backend/baton/src/main/java/touch/baton/domain/common/vo/Introduction.java
> +    public static Introduction getDefaultValue() {
메서드명도 바꿔주시면 좋을거 같아요!

2023-08-14 10:23 UTC, hyena0608 commented on backend/baton/src/main/java/touch/baton/domain/runner/Runner.java
> +            //return new Introduction(Introduction.getDefaultValue());
주석이 삭제가 안됐네요 ㅜ

2023-08-14 10:23 UTC, hyena0608 commented on backend/baton/src/main/java/touch/baton/domain/runnerpost/controller/response/SupporterRunnerPostResponse.java
> +        private static List<String> getTechnicalTags(final Supporter supporter) {
이 친구도 다른 친구들 처럼 convert... 어떤가요?

2023-08-14 10:23 UTC, hyena0608 commented on backend/baton/src/main/java/touch/baton/domain/runnerpost/service/RunnerPostService.java
> +        final List<SupporterRunnerPost> supporterRunnerPosts = supporterRunnerPostRepository.readByRunnerPostId(runnerPostId);
RunnerPost 내부에 있는 메서드로 getter 없이 진행할 수 있을거 같네요!

2023-08-14 10:23 UTC, hyena0608 commented on backend/baton/src/main/java/touch/baton/domain/supporter/Supporter.java
>      }
다른 부분 같지만 혹시 메서드명을 동사로 시작해주실 수 있나요?
그리고 null 체크를 내부만 해주는데 인자도 null인지 확인하면 좋을거 같아요~

2023-08-14 10:23 UTC, hyena0608 commented on backend/baton/src/test/java/touch/baton/assure/runnerpost/RunnerPostReadWithLoginedAssuredTest.java
> +        final SupporterRunnerPostResponse.Detail 서포토_러너_게시글_응답 = SupporterRunnerPostResponse.Detail.from(서포터_러너_게시글);
오타났어요!

2023-08-14 10:23 UTC, hyena0608 commented on backend/baton/src/test/java/touch/baton/assure/runnerpost/RunnerPostAssuredSupport.java
> +
.data() 안하시면 IntStream 돌리지 않으셔도 테스트 진행할 수 있을거 같아요.

2023-08-14 10:23 UTC, hyena0608 commented on backend/baton/src/test/java/touch/baton/assure/runnerpost/RunnerPostAssuredSupport.java
> +
작성하신 테스트에서 변수명을 '응답들' 이라고 하셔서 여기도 '응답들'로 파라미터명을 수정하면 좋을거 같아요!

2023-08-14 11:06 UTC, eunbii0213 commented on backend/baton/src/main/java/touch/baton/domain/runner/Runner.java
> +            //return new Introduction(Introduction.getDefaultValue());
OMG!!! 저 진짜 바본가봐요 ㅠ

2023-08-14 11:06 UTC, eunbii0213 commented on backend/baton/src/main/java/touch/baton/domain/runnerpost/controller/response/SupporterRunnerPostResponse.java
> +        private static List<String> getTechnicalTags(final Supporter supporter) {
오! 좋아요!!

2023-08-14 11:08 UTC, eunbii0213 commented on backend/baton/src/main/java/touch/baton/domain/runnerpost/service/RunnerPostService.java
> +        final List<SupporterRunnerPost> supporterRunnerPosts = supporterRunnerPostRepository.readByRunnerPostId(runnerPostId);
헤나 so 예리 boy!

2023-08-14 11:21 UTC, eunbii0213 commented on backend/baton/src/test/java/touch/baton/assure/runnerpost/RunnerPostAssuredSupport.java
> +
그럼 
assertThat(actual.data()).isEqualTo(서포터_러너_게시글_응답.data());
이렇게 가는 느낌인건가요?! 하나하나 값 꺼내서 검증하려고 (data안에 여러개의 post가 있을지 모르니까) 한거였었는데 다른 방법이 있는 건가요??

2023-08-15 05:28 UTC, cookienc commented on backend/baton/src/main/java/touch/baton/domain/supporter/repository/SupporterRunnerPostRepository.java
> +
depth는 굳이 필요 없죠

2023-08-15 05:28 UTC, cookienc commented on backend/baton/src/test/java/touch/baton/assure/runnerpost/RunnerPostReadWithLoginedAssuredTest.java
> +        final SupporterRunnerPostResponse.Detail 서포토_러너_게시글_응답 = SupporterRunnerPostResponse.Detail.from(서포터_러너_게시글);
헤나 폼 미쳤다..

2023-08-16 02:52 UTC, shb03323 commented on backend/baton/src/docs/asciidoc/RunnerPostReadApi.adoc
> +
코드 포매팅 해주세요!

2023-08-16 02:58 UTC, eunbii0213 commented on backend/baton/src/docs/asciidoc/RunnerPostReadApi.adoc
> +
이 부분 러너게시글전체조회 PR 머지되면 같이 적용 될 예정입니다!

2023-08-16 07:43 UTC, shb03323 commented on backend/baton/src/main/java/touch/baton/domain/common/vo/Introduction.java
> +        return new Introduction(DEFAULT_VALUE);
이거 데이터베이스 측에서는 defalut 설정하지 않고, 스프링에서만 default를 설정하고 데이터베이스에 넣어주면 어때요?
데이터베이스 default는 처음 db가 만들어질때만 설정되어서 변화시키기 어려울 것 같다고 생각했어요. 바꾸려면 ddl-auto를 create로 두거나 직접 sql로 바꾸는 수밖에 없습니다.

스프링에서 바꾸는 것이 변화에 더 유연할 것 같습니다.

그렇게 되면 DEFAULT_VALUE 를 "안녕하세요." 정도로만 설정하고 null 이라면 defalut 값을 넣어주는 것이 좋을 것 같아요.

또, 칼럼의 nullable을 false로 바꾸어주세요.

2023-08-16 07:47 UTC, shb03323 commented on backend/baton/src/main/java/touch/baton/domain/runnerpost/service/RunnerPostService.java
> +        return supporterRunnerPosts;
```suggestion
        return supporterRunnerPostRepository.readByRunnerPostId(runnerPostId);
```

2023-08-16 07:48 UTC, shb03323 commented on backend/baton/src/main/java/touch/baton/domain/runnerpost/service/RunnerPostService.java
> +            throw new RunnerPostBusinessException("RunnerPost 의 작성자가 다릅니다.");
RunnerPost 의 작성자가 아닙니다는 어떤가요? 주체는 본인이니까요.

2023-08-16 07:49 UTC, shb03323 commented on backend/baton/src/test/java/touch/baton/assure/runnerpost/RunnerPostReadWithLoginedAssuredTest.java
> +        final SupporterRunnerPost 서포터_러너_게시글 = supporterRunnerPostRepository.save(SupporterRunnerPostFixture.create(러너_게시글, 서포터_주디));
서포터_러너_게시글 보다는, 서포터의 리뷰 제안 으로 하면 어때요?

2023-08-16 07:50 UTC, shb03323 commented on backend/baton/src/test/java/touch/baton/assure/runnerpost/RunnerPostReadWithLoginedAssuredTest.java
> +        final SupporterRunnerPostResponses.Detail 서포터_러너_게시글_응답들 = SupporterRunnerPostResponses.Detail.from(List.of(서포터_러너_게시글_응답));
윗 댓글과 마찬가지입니당

2023-08-16 07:50 UTC, shb03323 commented on backend/baton/src/test/java/touch/baton/assure/runnerpost/RunnerPostReadWithLoginedAssuredTest.java
> +                .서포터_러너_게시글_조회_성공을_검증한다(서포터_러너_게시글_응답들);
리뷰 제안한 서포터 목록 조회 성공을 검증한다

2023-08-16 07:51 UTC, shb03323 commented on backend/baton/src/test/java/touch/baton/assure/supporter/SupporterAssuredSupport.java
> +                softly.assertThat(response.statusCode()).isEqualTo(http_상태.value());
이건 영어로 했었습니당

2023-08-16 07:51 UTC, shb03323 commented on backend/baton/src/test/java/touch/baton/assure/supporter/SupporterAssuredSupport.java
> +                softly.assertThat(response.statusCode()).isEqualTo(http_상태.value());
HTTP_STATUS

2023-08-16 07:52 UTC, shb03323 commented on backend/baton/src/test/java/touch/baton/assure/supporter/SupporterRunnerPostAssuredSupport.java
> +        public void 서포터의_리뷰_제안_철회를_검증한다(final HttpStatus http_상태,
HTTP_STATUS 2

2023-08-16 07:52 UTC, shb03323 commented on backend/baton/src/test/java/touch/baton/assure/supporter/SupporterRunnerPostAssuredSupport.java
> +                softly.assertThat(response.statusCode()).isEqualTo(http_상태.value());
HTTP_STATUS 3

2023-08-16 07:54 UTC, shb03323 commented on backend/baton/src/test/java/touch/baton/domain/runnerpost/RunnerPostTest.java
> +    }
id 가 있는 임의의 생성자를 더 만들 것 같아요.

2023-08-16 07:55 UTC, shb03323 requested changes
아자아자아자!!

2023-08-16 08:00 UTC, cookienc submitted a review, later dismissed
굳굳!!

2023-08-16 08:29 UTC, eunbii0213 commented on backend/baton/src/test/java/touch/baton/domain/runnerpost/RunnerPostTest.java
> +    }
이거 제가 작성한 게 아니긴한데 추가되어있더라구요~!!

2023-08-16 08:29 UTC, eunbii0213 commented on backend/baton/src/test/java/touch/baton/assure/supporter/SupporterAssuredSupport.java
> +                softly.assertThat(response.statusCode()).isEqualTo(http_상태.value());
다른거 다 한글이어서 살짝 고쳐봤었어요 ㅋㅎ 다시 바꾸겠습니당

2023-08-16 08:34 UTC, eunbii0213 commented on backend/baton/src/main/java/touch/baton/domain/common/vo/Introduction.java
> +        return new Introduction(DEFAULT_VALUE);
네! 그러면 @ColumnDefault를 삭제하겠습니다!

2023-08-16 08:36 UTC, eunbii0213 commented on backend/baton/src/main/java/touch/baton/domain/common/vo/Introduction.java
> +        return new Introduction(DEFAULT_VALUE);
대박 저렇게까지는 생각 못했는데 새로운 인사이트를 얻어가네요 감사합니다

2023-08-16 08:46 UTC, eunbii0213 commented on backend/baton/src/test/java/touch/baton/assure/runnerpost/RunnerPostReadWithLoginedAssuredTest.java
> +        final SupporterRunnerPost 서포터_러너_게시글 = supporterRunnerPostRepository.save(SupporterRunnerPostFixture.create(러너_게시글, 서포터_주디));
엇 이거 나중에 이슈 따로 파서 하자고 하지 않으셨나요?!

2023-08-16 08:56 UTC, eunbii0213 commented on backend/baton/src/test/java/touch/baton/assure/runnerpost/RunnerPostReadAssuredTest.java
> +    private Runner 러너를_저장한다(final Member 멤버) {
네!1 @hyena0608 코드 parameter도 같이 사용자로 바꿔주었습니다!

2023-08-16 08:57 UTC, eunbii0213 commented on backend/baton/src/test/java/touch/baton/fixture/domain/MessageFixture.java
> +public class MessageFixture {
어라?! 이미 abstract로 되어있어요!

2023-08-16 08:59 UTC, eunbii0213 commented on backend/baton/src/test/java/touch/baton/document/runnerpost/read/RunnerPostReadApiTest.java
> +
헤나~! 새로고침 한 번 하시구 리뷰 주셔야해용~!!

2023-08-16 09:04 UTC, eunbii0213 commented on backend/baton/src/test/java/touch/baton/domain/runnerpost/RunnerPostTest.java
> +    }
dev/BE엔 지워졌는데 제가 conflict해결하면서 넣어버렸나봐용 ㅎㅎ.. 지우겠슴다

2023-08-16 09:08 UTC, eunbii0213 commented on backend/baton/src/test/java/touch/baton/domain/runnerpost/RunnerPostTest.java
> +        assertThat(runnerPost.getRunnerPostTags().getRunnerPostTags()).hasSize(2);
좋아요!!! 그런데 conflict를 해결하면서 제가 작성하지 않았던 코드를 추가하면서 제가 작성한 걸로 되거나, 제가 작성했던 코드가 사라지거나, 삭제했던 게 삭제되어있지 않는 문제가 가끔 있네요. 더 신경써서 conflict를 해야겠습니다. 좀 어렵네요 ㅋㅋㅋㅋ

2023-08-16 09:14 UTC, eunbii0213 commented on backend/baton/src/main/java/touch/baton/domain/common/vo/Introduction.java
> +        return new Introduction(DEFAULT_VALUE);
어.. 그런데 디투! 그렇게 되면 nullable = false로 하면 안 되지 않나요?? 그럼 null이면 introduction을 기본으로 설정하는 것이 아닌, introduction에 null이 들어오자마자 터져버려요!

2023-08-16 09:16 UTC, eunbii0213 commented on backend/baton/src/main/java/touch/baton/domain/common/vo/Introduction.java
> +        return new Introduction(DEFAULT_VALUE);
사실 nullable이어도 상관 없을 것 같은게 저희 로직에서는 null인지, 아닌지를 검사한 다음에 기본값을 설정해줘서 null이 들어와도 Null값으로 저장이 되거나 할 일은 없을 것 같다는 입장이에요! 디투는 어떻게 생각하시나요??

2023-08-16 09:46 UTC, cookienc requested changes

2023-08-16 09:46 UTC, cookienc commented on backend/baton/src/main/java/touch/baton/domain/supporter/Supporter.java
> +        updateIntroduction(introduction);
요건 메서드 명이 udpate에서 쓴는 걸로 되어있는데 실제로는 생성자에서 사용되니까 원하는대로 동작하지 않을것 같네요

2023-08-16 09:46 UTC, cookienc commented on backend/baton/src/test/java/touch/baton/domain/runnerpost/RunnerPostTest.java
> +        final List<RunnerPostTag> runnerPostTags = runnerPost.getRunnerPostTags().getRunnerPostTags();
then절에 있는게 적절해 보여요

2023-08-16 09:46 UTC, cookienc commented on backend/baton/src/test/java/touch/baton/domain/runnerpost/RunnerPostTest.java
> +        assertThat(runnerPostTags.get(1).getTag().getTagName().getValue()).isEqualTo("Spring");
1. softAssertions으로 검증 해주세요.
2. containsExactly()를 사용해보면 어떨까요?

2023-08-16 09:46 UTC, hyena0608 commented on backend/baton/src/main/java/touch/baton/domain/runnerpost/service/RunnerPostService.java
> +        }
혹시 검증을 넣으신 이유가 있으신가요?

2023-08-16 09:46 UTC, hyena0608 commented on backend/baton/src/main/java/touch/baton/domain/supporter/Supporter.java
> +        updateIntroduction(introduction);
검증과 업데이트가 같이 있는게 아쉽다고 느껴집니다

2023-08-16 09:48 UTC, eunbii0213 commented on backend/baton/src/main/java/touch/baton/domain/runnerpost/service/RunnerPostService.java
> +        }
일반적인 서비스처람 글 작성자만 지원한 서포터의 목록을 볼 수 있어야한다고 생각했기 때문입니다!

2023-08-16 09:49 UTC, eunbii0213 commented on backend/baton/src/main/java/touch/baton/domain/supporter/Supporter.java
> +        updateIntroduction(introduction);
네 저도 그렇게 생각합니다. 하지만 디투가 앞에서 코멘트 줬던 것 처럼 오직 spring에서만 기본값처리를 해주고 있기 때문에 생성자에서 업데이트 처리를 해주지 않으면 생성 때 초기값이 들어가지 않습니다 ㅜ 그렇다고 새로운 메서드를 추가하자니 중복된 로직이 생겨버리더라구요. 혹시 더 좋은 의견 있으신가요??

2023-08-16 10:24 UTC, eunbii0213 commented on backend/baton/src/main/java/touch/baton/domain/supporter/Supporter.java
> +        updateIntroduction(introduction);
update할 때랑, 생성할 때랑 둘 다 사용됩니다!!

2023-08-16 11:22 UTC, shb03323 commented on backend/baton/src/main/java/touch/baton/domain/common/vo/Introduction.java
> +        return new Introduction(DEFAULT_VALUE);
ddl 에서 터진다는 것은 데이터베이스에 null 값이 들어갔다는 거에요. 데이터베이스에 null이 들어가지 않게 조절하면 되지 않을까요?

Introduction 객체 값으로 null이 들어가면 터지지 않을 것이고, 데이터베이스로 들어가게 되면 터지게 되겠죵?

>사실 nullable이어도 상관 없을 것 같은게 저희 로직에서는 null인지, 아닌지를 검사한 다음에 기본값을 설정해줘서 null이 들어와도 Null값으로 저장이 되거나 할 일은 없을 것 같다는 입장이에요! 디투는 어떻게 생각하시나요??

그렇다면 모든 칼럼을 nullable로 설정해두어도 되는 것 아닌가요?
역으로 null이 들어올 일이 없는데 nullable을 허용하는 이유가 궁금합니다!

2023-08-16 11:24 UTC, eunbii0213 commented on backend/baton/src/main/java/touch/baton/domain/common/vo/Introduction.java
> +        return new Introduction(DEFAULT_VALUE);
아!!!!!!!!!!!!!!! 혹시!!!!!!!! 아!!!!! 그렇구나!!!!!! 뭔말알!!!!!!!!! 잠시만요!!!! 도전

2023-08-16 11:30 UTC, eunbii0213 commented on backend/baton/src/main/java/touch/baton/domain/common/vo/Introduction.java
> +        return new Introduction(DEFAULT_VALUE);
그럼 update문에다가만 넣어두어야 하는 거 맞죠??
러너 생성할 때 초기값을 코드단에서 (private Introduction introduction = Introduction.getDefaultIntroduction();)이런식으로 해줬으니까 update할 때만 신경쓰면 되는 거잖아요!!

2023-08-16 11:41 UTC, shb03323 commented on backend/baton/src/test/java/touch/baton/assure/runnerpost/RunnerPostReadWithLoginedAssuredTest.java
> +        final SupporterRunnerPost 서포터_러너_게시글 = supporterRunnerPostRepository.save(SupporterRunnerPostFixture.create(러너_게시글, 서포터_주디));
테이블 명과 설명하는 문구는 다르다고 생각했어요.
설명할 때는 최대한 시나리오처럼 보여야 한다고 생각해요. 지금 주디가 작성한 코드는 시나리오잖아요.
그래서 영어보다는 한국어로 작성한 것이구요.

코드를 모르는 기획자가 보았을 때 서포터_러너_게시글이 무엇인지 알 수 있을까요?
클라이언트 개발자는 알 수 있을까요?
`서포터_러너_게시글`은 변수명을 한국어로 직역한 것으로밖에 보이지 않아서요ㅠㅠ

2023-08-16 11:59 UTC, eunbii0213 commented on backend/baton/src/main/java/touch/baton/domain/common/vo/Introduction.java
> +        return new Introduction(DEFAULT_VALUE);
으아아악 드디어 한 것 같은데 이걸 원했던 건지 코드리뷰로 봐주십쇼
<img width="666" alt="스크린샷 2023-08-16 오후 8 59 16" src="https://github.com/woowacourse-teams/2023-baton/assets/67318165/4f31f219-5e8c-43d0-b31e-715e9829ef31">

2023-08-16 12:02 UTC, shb03323 commented on backend/baton/src/main/java/touch/baton/domain/supporter/Supporter.java
> +        updateIntroduction(introduction);
생성 시에 null을 검증해야할까요?

2023-08-16 12:05 UTC, eunbii0213 commented on backend/baton/src/main/java/touch/baton/domain/supporter/Supporter.java
> +        updateIntroduction(introduction);
혹시 왜 안 해도 되는건가요?? 혹시 생성자로 Null이 들어온다면 기본값으로 바꿔주려고해서 그런건데!

2023-08-16 12:06 UTC, eunbii0213 commented on backend/baton/src/main/java/touch/baton/domain/supporter/Supporter.java
> +        updateIntroduction(introduction);
객체에는 null이 들어와도 되고 DB엔 안된다는 게 코드에 어떻게 적용이 되는건지 너무 헷갈려요. 어디서 막아주는 게 맞는건지 잘 모르겠어요. 생성할 때, update 검증해야하는 것 아닌가요??

2023-08-16 12:16 UTC, eunbii0213 commented on backend/baton/src/main/java/touch/baton/domain/supporter/Supporter.java
> +        updateIntroduction(introduction);
혹시 생성자에서 Null검증을 하지 않아도 된다는 말이 (테스트 코드에서든 실제든) null이 들어와도 상관없고 어찌됐든 DB에만 저장이 안 되면 된다는 의미로 이해가 되기도 해요. 만약 제가 잘 이해한 게 맞다면 처음 생성할 때 introduction이 null이 들어올 수 있을 것 같은데 이건 어디서 막아줘야하나요? service라고하기에는 우린 runner와 supporter을 생성하는 API가 존재하지 않고..조회할 때 바꿔주는 것도 로직이 이상하고요.. 흠.. 그래서 고민하다가 결국 생성자밖에 넣을 곳이 없다 판단한 것 같아요.

2023-08-16 12:19 UTC, shb03323 commented on backend/baton/src/main/java/touch/baton/domain/supporter/Supporter.java
> +        updateIntroduction(introduction);
수정할 때만 받아요.
그렇다면 수정할때만 null check 하면 될 것 같아요.

2023-08-16 12:21 UTC, eunbii0213 commented on backend/baton/src/main/java/touch/baton/domain/supporter/Supporter.java
> +        updateIntroduction(introduction);
엇 받지 않나요?? 생성자에 introduction 있어요!

2023-08-16 12:43 UTC, eunbii0213 commented on backend/baton/src/test/java/touch/baton/domain/runnerpost/RunnerPostTest.java
> +        final List<RunnerPostTag> runnerPostTags = runnerPost.getRunnerPostTags().getRunnerPostTags();
수정하겠습니다! 그런데 전 then절에 Assertions~~ 만 넣는 걸 선호하긴 한데 혹시 컨벤션이었나요??

2023-08-16 13:21 UTC, hyena0608 commented on backend/baton/src/main/java/touch/baton/domain/runner/Runner.java
> +    private Introduction introduction = Introduction.getDefaultIntroduction();
id가 없는 생성자에서 introduction을 안받아도 괜찮을거 같다는 생각이 듭니다.

2023-08-16 13:21 UTC, hyena0608 commented on backend/baton/src/main/java/touch/baton/domain/supporter/Supporter.java
> +    private Introduction introduction = Introduction.getDefaultIntroduction();
Runner 커멘트와 같은 생각입니다.

2023-08-16 13:21 UTC, hyena0608 commented on backend/baton/src/main/java/touch/baton/domain/supporter/Supporter.java
> +    private Introduction validateIntroductionNotNull(final Introduction introduction) {
validate라는 메서드가 반환하는게 기존 메서드명과는 다른 느낌이 들어 헷갈리는 느낌이 있는거 같아요.
또한 Runner 커멘트와 같은 내용입니다.

2023-08-16 13:21 UTC, hyena0608 commented on backend/baton/src/test/java/touch/baton/domain/runnerpost/RunnerPostTest.java
> +
사소한거지만 두칸이에요!~

2023-08-16 13:21 UTC, hyena0608 commented on backend/baton/src/test/java/touch/baton/fixture/domain/MessageFixture.java
> +public class MessageFixture {
확인해주세요~

2023-08-16 13:21 UTC, shb03323 commented on backend/baton/src/main/java/touch/baton/domain/runner/Runner.java
> +            return Introduction.getDefaultIntroduction();
위의 member 처럼 만약 introduction이 null 이라면 그저 예외만 발생시켜주면 될 것 같아요. 예외 검증이 되었다면 introduction을 저장하구요.

2023-08-16 13:25 UTC, eunbii0213 commented on backend/baton/src/main/java/touch/baton/domain/runner/Runner.java
> +            return Introduction.getDefaultIntroduction();
예외를 발생시킨다면 Introduction 객체에도 null저장을 허용하지 않는다는 의미 아닌가요?ㅅ? 저는 그렇게 이해하고 null 체크를 진행한 것이었습니다! 
- Introduction 객체에 null이 들어온다면 기본값을 넣어줌
- null이 아닌 정상적인 값이 들어왔다면 요청대로의 값을 넣어줌 
이렇게 생각했어요!

2023-08-16 13:38 UTC, eunbii0213 commented on backend/baton/src/main/java/touch/baton/domain/runner/Runner.java
> +    private Introduction introduction = Introduction.getDefaultIntroduction();
혹시 왜 그렇게 생각하시는지 여쭤봐도 될까요??

2023-08-16 13:39 UTC, eunbii0213 commented on backend/baton/src/main/java/touch/baton/domain/supporter/Supporter.java
> +    private Introduction validateIntroductionNotNull(final Introduction introduction) {
으음 그럼 getDefaultIntroductionIfNull이란 메서드명은 어떤가요?

2023-08-16 14:20 UTC, eunbii0213 commented on backend/baton/src/main/java/touch/baton/domain/runner/Runner.java
> +            return Introduction.getDefaultIntroduction();
만약 예외만 발생시킨다면 어떻게 기본값이 저장되어야한다고 생각하는지도 궁금합니다!

2023-08-16 14:47 UTC, hyena0608 commented on backend/baton/src/main/java/touch/baton/domain/runner/Runner.java
>      }
요 생성자는 데이터베이스에서 받아올 때 사용해서 introduction 있어야할 거 같아요~

2023-08-16 14:47 UTC, hyena0608 commented on backend/baton/src/main/java/touch/baton/domain/runner/Runner.java
> +        return this.introduction = validateIntroductionNotNull(introduction);
반환값을 갖게된 이유가 궁금해요~

2023-08-16 14:47 UTC, hyena0608 commented on backend/baton/src/main/java/touch/baton/domain/supporter/Supporter.java
> +    private Introduction validateIntroductionNotNull(final Introduction introduction) {
이건 디에의 이야기를 듣고 진행하시죠~

2023-08-16 14:47 UTC, hyena0608 commented on backend/baton/src/test/java/touch/baton/domain/runnerpost/RunnerPostTest.java
> +        final List<RunnerPostTag> runnerPostTags = runnerPost.getRunnerPostTags().getRunnerPostTags();
저는 when절에 넣더라도 개행을 추가해서 중요하지 않다는 거를 의미하는 방식을 주로합니다.
Then 절에 작성해서 단순히 검증을 위해서 어떤 행위를 했다고 나타내기도 합니다.

When절에 해당하는 것처럼 보여지긴해서 좀 더 확실하게 구분 짓는게 좋을거 같다고 생각이 들긴합니다~

2023-08-16 14:48 UTC, eunbii0213 commented on backend/baton/src/main/java/touch/baton/domain/runner/Runner.java
>      }
아이고 저도 빈사상태라 id있는 거 까지 빼버렸군요 ㅋㅋㅋㅋ;

2023-08-16 14:48 UTC, eunbii0213 commented on backend/baton/src/main/java/touch/baton/domain/runner/Runner.java
>      }
죄송합니다 냅다 수정할게요

2023-08-16 14:55 UTC, shb03323 commented on backend/baton/src/main/java/touch/baton/domain/runner/Runner.java
> +    private Introduction introduction = Introduction.getDefaultIntroduction();
저는 Introduction 객체 안의 역할이라고 생각해요.

2023-08-16 14:56 UTC, eunbii0213 commented on backend/baton/src/main/java/touch/baton/domain/runner/Runner.java
> +        return this.introduction = validateIntroductionNotNull(introduction);
반환값이 무조건 있어야하는 건 아니었어요!
this. ~~~ 이런식으로 설정해주고 void를 return 해도 상관없어서 그렇게 수정하겠습니다!

2023-08-16 15:12 UTC, hyena0608 commented on backend/baton/src/main/java/touch/baton/domain/runner/Runner.java
>      }
화이티이이이이이이이잉~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~!!!

2023-08-16 15:37 UTC, merged