서포터의 리뷰 제안 철회 API 구현
woowacourse-teams/2023-baton pull request #337
Opened 2023-08-13 07:24 UTC by shb03323

## 관련이슈

- resolved #332

## 참고사항
- RestAssuredTest 중에 인자로 레포지토리 관련 로직을 넣었습니다. 다른 방법을 모르겠습니다. 알려주신다면 감사.

2023-08-13 08:14 UTC, cookienc requested changes
굳굳!

2023-08-13 08:14 UTC, cookienc commented on backend/baton/src/main/java/touch/baton/domain/runnerpost/service/RunnerPostService.java
> +                .orElseThrow(() -> new ClientRequestException(RUNNER_POST_NOT_FOUND));
저는 이걸 business 예외라고 보는데 어떻게 생각하시나요? 아래도 마찬가지입니다. 왜냐면 클라이언트의 역할은 값이 제대로 들어갔는지나 길이가 맞는지와 같은 정보를 확인하는 역할이라고 생각하기 때문입니다. service에서 client 예외를 발생시키면 클라이언트가 값을 보낼 때 이 값이 존재하는지에 대한 정보를 알고 있다고 가정하는 것과 비슷하다고 생각이 듭니다.

2023-08-13 08:14 UTC, cookienc commented on backend/baton/src/test/java/touch/baton/domain/runnerpost/service/RunnerPostServiceUpdateTest.java
> +    @Nested
저희 도메인에서만 nested 쓰기로 하지 않았나요?

2023-08-13 08:14 UTC, cookienc commented on backend/baton/src/test/java/touch/baton/domain/supporter/repository/SupporterRunnerPostRepositoryTest.java
> +    private EntityManager entityManager;
저희 repository에서 entity manager 쓰는걸로 정했나용?

2023-08-13 08:14 UTC, cookienc commented on backend/baton/src/test/java/touch/baton/assure/supporter/SupporterRunnerPostDeleteAssuredTest.java
> +                .서포터의_리뷰_제안_철회를_검증한다(NO_CONTENT, 응답_헤더_이름, 응답_헤더_값, supporterRunnerPostRepository.existsById(서포터의_리뷰_제안.getId()));
저는 인수테스트에서 따로 성공적으로 등록이나 변경되었는지 작성하는 편이 아닙니다. 어쩔수 없이 repositroy 로직과의 연관관계 생겨서요. 개인적으로는 service에서 검증하는 것만으로도 충분하다고 생각이들어요. 만약 쓴다면 메서드 분리할거 같네요

2023-08-13 10:16 UTC, shb03323 commented on backend/baton/src/main/java/touch/baton/domain/runnerpost/service/RunnerPostService.java
> +                .orElseThrow(() -> new ClientRequestException(RUNNER_POST_NOT_FOUND));
클라이언트 예외의 범위는 request body 뿐만 아니라 path parameter 까지도 된다고 생각해요. 넣어준 id가 잘못되었으니 찾을 수 없다고 생각했어요. 만약 존재하는데 찾지 못하는 것이라면 서버 예외겠지만, 클라이언트로부터 들어온 입력값이 잘못된 것이라면 400번대 에러를 띄우는게 좋은 것 같아요.
서비스가 클라이언트를 안다는 것이 아쉽지만, 비즈니스 예외로 터트리면 500 에러밖에 반환하지 못하기 때문에 어쩔 수 없다고 생각했어요.

2023-08-13 10:17 UTC, shb03323 commented on backend/baton/src/test/java/touch/baton/domain/runnerpost/service/RunnerPostServiceUpdateTest.java
> +    @Nested
sorry

2023-08-13 10:18 UTC, shb03323 commented on backend/baton/src/test/java/touch/baton/domain/supporter/repository/SupporterRunnerPostRepositoryTest.java
> +    private EntityManager entityManager;
정하지 않았어요. 이야기 해보아야합니다.

2023-08-13 10:19 UTC, shb03323 commented on backend/baton/src/test/java/touch/baton/assure/supporter/SupporterRunnerPostDeleteAssuredTest.java
> +                .서포터의_리뷰_제안_철회를_검증한다(NO_CONTENT, 응답_헤더_이름, 응답_헤더_값, supporterRunnerPostRepository.existsById(서포터의_리뷰_제안.getId()));
input 과 output 만 검증하는 것이 인수테스트이기 때문에 역할 외의 것을 하는 듯한 느낌은 들어요. 다른 분들 생각은 어떠신가요?

2023-08-13 12:12 UTC, shb03323 commented on backend/baton/src/test/java/touch/baton/domain/runnerpost/service/RunnerPostServiceUpdateTest.java
> +    @Nested
흠. 클래스 분리는 어떻게 생각해요?

2023-08-13 12:19 UTC, cookienc commented on backend/baton/src/main/java/touch/baton/domain/runnerpost/service/RunnerPostService.java
> +                .orElseThrow(() -> new ClientRequestException(RUNNER_POST_NOT_FOUND));
음 이건 다른 사람의 의견도 같이 물어봐야겠어요 @hyena0608  @eunbii0213

2023-08-13 12:49 UTC, hyena0608 commented on backend/baton/src/main/java/touch/baton/domain/runnerpost/service/RunnerPostService.java
> +                .orElseThrow(() -> new ClientRequestException(RUNNER_POST_NOT_FOUND));
저는 서버 에러가 더 나을거 같아요.
400은 사용자가 잘못한거라고 느껴지는데 예를 들어 프론트 측에서 버튼을 연속으로 누르지 못하도록 막아놨는데 어떻게든 서버 내부로 해당 값이 들어와서 로직을 타게된다면 어디선가 서버에서 잘못된거 아닐까라는 생각입니다.

만약 처리가 안되어있다면 사용자가 잘못했기에 400이 맞을거 같지만 결국에는 못하게 처리할거고
400이라면 서비스 계층에 컨트롤러 단의 내용이 들어온 거 같다는 느낌입니다~

2023-08-13 12:49 UTC, hyena0608 commented on backend/baton/src/main/java/touch/baton/domain/runnerpost/service/RunnerPostService.java
> +        }
삭제했는데 deleteCount가 0이 나오는 경우면 이미 삭제되었기 때문에 그런것이라 성공 띄어줘도 괜찮을거 같다는 생각입니다!

2023-08-13 12:49 UTC, hyena0608 commented on backend/baton/src/test/java/touch/baton/assure/supporter/SupporterRunnerPostDeleteAssuredTest.java
> +                .서포터의_리뷰_제안_철회를_검증한다(NO_CONTENT, 응답_헤더_이름, 응답_헤더_값, supporterRunnerPostRepository.existsById(서포터의_리뷰_제안.getId()));
저는 아예 다른 인수테스트를 만들고 그 밑에 가져다가 붙여서 한 스토리를 만듭니다~
그냥 repository 조회로 검증하는거는 조금 아쉽네요!

2023-08-13 12:49 UTC, hyena0608 commented on backend/baton/src/test/java/touch/baton/document/runnerpost/read/RunnerPostUpdateSupporterCancelationApiTest.java
> +                        responseHeaders(headerWithName(LOCATION).description("redirect uri"))
```suggestion
                        responseHeaders(
                                headerWithName(LOCATION).description("redirect uri")
                         )
```

별거는 아니지만 위에 다 띄어져 있어서 슬쩍 커멘트 남겨봐요

2023-08-13 14:13 UTC, shb03323 commented on backend/baton/src/main/java/touch/baton/domain/runnerpost/service/RunnerPostService.java
> +        }
찾지 못한 경우도 있을 것 같은데 어떻게 생각하시나요

2023-08-13 14:13 UTC, shb03323 commented on backend/baton/src/main/java/touch/baton/domain/runnerpost/service/RunnerPostService.java
> +        }
쿼리를 한 번 더 쓰기엔 아쉬워서요

2023-08-13 14:16 UTC, eunbii0213 commented on backend/baton/src/main/java/touch/baton/domain/runnerpost/service/RunnerPostService.java
> +                .orElseThrow(() -> new ClientRequestException(RUNNER_POST_NOT_FOUND));
저도 헤나의 의견에 동의합니다!!

2023-08-14 07:06 UTC, hyena0608 approved these changes

2023-08-14 07:06 UTC, cookienc approved these changes

2023-08-14 07:07 UTC, merged