러너 게시글 전체 조회 API 페이징 기능 추가
woowacourse-teams/2023-baton pull request #344
Opened 2023-08-13 18:52 UTC by eunbii0213

## 관련이슈

- resolved #339 

## 참고사항
원래 디투가 하기로 했었는데 다시 뺏어왔습니다.
시간은 많이 걸리겠지만 최대한 할 수 있는 건 해보고 싶었기도하고
디투가 힘들어보여서 조금이라도 도움이 되었으면 하는 마음이었습니다.
헤나 것도 뺏어오고 싶었는데 그것까지는 못해서 아쉽네요. 다음엔 꼭 뺏어보겠습니다.
잘 부탁드립니다.

2023-08-14 06:04 UTC, hyena0608 commented on backend/baton/src/test/java/touch/baton/domain/runnerpost/repository/read/RunnerPostRepositoryReadTest.java
> +//    @DisplayName("RunnerPost 최신 순으로 전체 조회한다.")
🤔?

2023-08-14 06:07 UTC, cookienc approved these changes
LGTM!

2023-08-14 06:07 UTC, cookienc commented on backend/baton/src/main/java/touch/baton/domain/runnerpost/controller/response/RunnerPostResponse.java
> +                                  final int applicantCount) {
요것도 long으로 바꿔주세요

2023-08-14 06:07 UTC, cookienc commented on backend/baton/src/main/java/touch/baton/domain/runnerpost/controller/RunnerPostController.java
> +//    }
안 쓰는 건 지워도 될 것 같아요

2023-08-14 06:07 UTC, cookienc commented on backend/baton/src/test/java/touch/baton/domain/runnerpost/repository/read/RunnerPostRepositoryReadTest.java
> +//    @Test
안쓰는건 삭제해주세요

2023-08-14 10:08 UTC, eunbii0213 commented on backend/baton/src/test/java/touch/baton/domain/runnerpost/repository/read/RunnerPostRepositoryReadTest.java
> +//    @DisplayName("RunnerPost 최신 순으로 전체 조회한다.")
이거 지워도 될지 말지 모르겠어서 일단 주석처리해놨어요! 슬랙에서도 구현 이미 한 거 지워도 되냐고 물었었는데 아직 대답이 없어서..ㅎㅅㅎ

2023-08-14 10:09 UTC, eunbii0213 commented on backend/baton/src/test/java/touch/baton/domain/runnerpost/repository/read/RunnerPostRepositoryReadTest.java
> +//    @Test
지워도 되는거군요! 슬랙에 물었었는데 아직 답장이 없으셔서 일단 주석처리해놓고 기다리고 이있었어요!!

2023-08-14 10:18 UTC, eunbii0213 commented on backend/baton/src/main/java/touch/baton/domain/runnerpost/controller/RunnerPostController.java
> +        return applicantCounts.get(index);
이 로직이 없으면 Applicant가 0일 때 에러가 발생하더라구요 🥲
List(applicantCounts) size가 0인데 뭘 꺼내오라는거냐 면서 싫다고 했어요🥲

2023-08-14 10:28 UTC, hyena0608 commented on backend/baton/src/main/java/touch/baton/domain/runnerpost/controller/RunnerPostController.java
> +        return applicantCounts.get(index);
이 부분이 서포터로 러너 게시글을 찾아오는게 아니라서 그런거 같네요.
컨트롤러 말고 서비스단에서 applicantCount 가져오는 부분을 리팩터링 해보셔도 좋을거 같아요~

2023-08-14 10:31 UTC, hyena0608 commented on backend/baton/src/main/java/touch/baton/domain/runnerpost/controller/RunnerPostController.java
> +        final List<Integer> applicantCounts = collectApplicantCounts(pageRunnerPosts);
이제 Long으로 변경된거 혹시 몰라서 커멘트 달아만 놓을게요~

2023-08-14 10:31 UTC, hyena0608 commented on backend/baton/src/test/java/touch/baton/assure/runnerpost/RunnerPostReadAssuredTest.java
> +
여기 붙여주실 수 있나요?

2023-08-14 11:02 UTC, eunbii0213 commented
이제.. 슬슬 힘들군요.. 끝까지 화이링~!!!!

2023-08-15 05:15 UTC, cookienc requested changes
확인해주세요💪

2023-08-15 05:15 UTC, cookienc commented on backend/baton/src/main/java/touch/baton/domain/runnerpost/repository/RunnerPostRepository.java
> +    Page<RunnerPost> findAll(Pageable pageable);
findal 이 없네요

2023-08-15 05:15 UTC, cookienc commented on backend/baton/src/main/java/touch/baton/domain/runnerpost/service/RunnerPostService.java
>      }
1. 요 로직이 추가된 이유는 무엇인가요? 
2. application.size() == 0 보다는 isEmpty()로 확인하는게 적절해보입니다

2023-08-15 05:15 UTC, cookienc commented on backend/baton/src/test/java/touch/baton/assure/runnerpost/RunnerPostReadAssuredTest.java
> +public class RunnerPostReadAssuredTest extends AssuredTestConfig {
public이 들어갔네요

2023-08-15 05:15 UTC, cookienc commented on backend/baton/src/test/java/touch/baton/document/runnerpost/read/RunnerPostReadAllApiTest.java
> +                .thenReturn(pageRunnerPosts);
불필요한 줄바꿈처럼 보이는데 어떻게 생각하세요? 아래도 마찬가지입니다

2023-08-15 05:15 UTC, cookienc commented on backend/baton/src/test/java/touch/baton/document/runnerpost/read/RunnerPostReadAllApiTest.java
> +                                fieldWithPath("pageInfo.currentSize").type(NUMBER).description("현재 페이지 데이터 수")
페이징 기능을 추가했는데 restdocs를 만드는 부분에는 페이징관련 요청 정보가 없네요

2023-08-15 05:15 UTC, cookienc commented on backend/baton/src/test/java/touch/baton/domain/runnerpost/repository/read/RunnerPostRepositoryReadTest.java
> +
안쓰는게 autowired 되어있네요

2023-08-15 05:15 UTC, cookienc commented on backend/baton/src/test/java/touch/baton/domain/runnerpost/repository/read/RunnerPostRepositoryReadTest.java
> +
안 쓰는 것들이네요

2023-08-16 01:40 UTC, eunbii0213 commented on backend/baton/src/main/java/touch/baton/domain/runnerpost/service/RunnerPostService.java
>      }
이 로직이 없으면 Applicant가 0일 때 에러가 발생하더라구요 🥲
List(applicantCounts이 부분이 서포터로 러너 게시글을 찾아오는게 아니라서 그런거 같아요! 이 코드가 처음엔 컨트롤러에 있었는데, 서비스단으로 옮기고 applicantCount 가져오는 부분을 리팩터링 한 것이었습니다!

2023-08-16 01:51 UTC, eunbii0213 commented on backend/baton/src/test/java/touch/baton/document/runnerpost/read/RunnerPostReadAllApiTest.java
> +                .thenReturn(pageRunnerPosts);
전반적인 테스트 코드에 .thenReturn 부분 수정 작업 들어가도록 하겠습니다!
붙여서 써도 길지 않을 때(코드가 한 화면에 다 들어올 때)는 내리지 않겠습니다!

2023-08-16 01:59 UTC, eunbii0213 commented on backend/baton/src/test/java/touch/baton/document/runnerpost/read/RunnerPostReadAllApiTest.java
> +                                fieldWithPath("pageInfo.currentSize").type(NUMBER).description("현재 페이지 데이터 수")
헉!! 냅다 추가하겠슴다!!

2023-08-16 03:01 UTC, shb03323 submitted a review, later dismissed
LGTM

2023-08-16 03:19 UTC, hyena0608 commented on backend/baton/src/test/java/touch/baton/assure/runnerpost/RunnerPostReadAssuredTest.java
> +class RunnerPostReadAssuredTest extends AssuredTestConfig {
```suggestion

@SuppressWarnings("NonAsciiCharacters")
class RunnerPostReadAssuredTest extends AssuredTestConfig {
```
문제되지 않는 부분이지만 붙여주셔도 좋을거 같아요!

2023-08-16 03:19 UTC, hyena0608 commented on backend/baton/src/test/java/touch/baton/assure/runnerpost/RunnerPostReadAssuredTest.java
> +    private Runner 러너를_저장한다(final Member member) {
```suggestion
    private Runner 러너를_저장한다(final Member 사용자) {
```

2023-08-16 03:19 UTC, hyena0608 commented on backend/baton/src/test/java/touch/baton/document/runnerpost/read/RunnerPostReadAllApiTest.java
> +                                fieldWithPath("pageInfo.currentSize").type(NUMBER).description("현재 페이지 데이터 수")
query parameters에 size, page 정보 추가해주시면 좋을거 같습니다!

2023-08-16 03:44 UTC, eunbii0213 commented on backend/baton/src/test/java/touch/baton/document/runnerpost/read/RunnerPostReadAllApiTest.java
> +                                fieldWithPath("pageInfo.currentSize").type(NUMBER).description("현재 페이지 데이터 수")
엑! 이거 추가했는데 conflict해결하는 과정에서 잘못가져왔던걸까요?? ㅋㅋㅋ이상하네요... 다시 넣겠습니다!!

2023-08-16 03:59 UTC, cookienc submitted a review, later dismissed
고생했어요!

2023-08-16 04:08 UTC, hyena0608 approved these changes
고생하셨어요~~

2023-08-16 04:09 UTC, merged