가이드라인 컴포넌트 추가
woowacourse-teams/2023-baton pull request #447
Opened 2023-09-07 05:58 UTC by tkdrb12

## 관련이슈

- resolved #375
- 가이드라인 컴포넌트 추가

## 참고사항
- 충돌 이슈를 고려해 글 작성페이지에 컴포넌트를 추가하지 않음

2023-09-07 06:30 UTC, gyeongza requested changes
코멘트 확인 부탁해요~ 그리구 구현한 화면 캡쳐본 올리면 좋을 것 같아요!

2023-09-07 06:30 UTC, gyeongza commented on frontend/src/components/GuideTextarea/GuideTextarea.tsx
> +  handleInputTextState: (e: React.ChangeEvent<HTMLTextAreaElement>) => void;
상태에 관한 네이밍을 통일해봐야겠네요 state를 붙여주면 명시적이긴한데 길어지는 단점이 있고해서 한번 얘기해봅시당

2023-09-07 06:30 UTC, gyeongza commented on frontend/src/components/GuideTextarea/GuideTextarea.tsx
> +  const [IsAnimated, setIsAnimated] = useState(false);
```suggestion
  const [isAnimated, setIsAnimated] = useState(false);
```

2023-09-07 06:30 UTC, gyeongza commented on frontend/src/components/GuideTextarea/GuideTextarea.tsx
> +    }
```suggestion
    if (!isAnimated) {
      setIsAnimated(true);
    }
```

2023-09-07 06:30 UTC, gyeongza commented on frontend/src/components/GuideTextarea/GuideTextarea.tsx
> +  }
여기는 이미 소문자로 되어있네요??

2023-09-07 06:37 UTC, guridaek approved these changes
LGTM!
수고했어요

2023-09-07 06:40 UTC, tkdrb12 commented on frontend/src/components/GuideTextarea/GuideTextarea.tsx
> +  const [IsAnimated, setIsAnimated] = useState(false);
어...?

2023-09-07 06:45 UTC, tkdrb12 commented on frontend/src/components/GuideTextarea/GuideTextarea.tsx
> +  handleInputTextState: (e: React.ChangeEvent<HTMLTextAreaElement>) => void;
피드백 반영 완료했습니다!

2023-09-11 04:07 UTC, gyeongza approved these changes

2023-09-11 04:07 UTC, merged