Feat/450
woowacourse-teams/2023-baton pull request #451
Opened 2023-09-10 12:04 UTC by shb03323

## 관련이슈

- resolved #450 

## 참고사항
칼럼 3개 TEXT 자료형으로 추가했습니다.

기존 스크립트에서 수정하고 싶은 부분이 있어서 수정했는데 어떻게 생각하시나요?

review_status : varchar(255) -> enum ('DONE', 'IN_PROGRESS', 'NOT_STARTED', 'OVERDUE')

review_type: enum ('BAD', 'GOOD', 'GREAT') -> enum ('BAD', 'GOOD', 'GREAT') -> 기존과 동일. 저는 varchar로 되어있을 줄 알았는데 아니더라구요. 다들 varchar로 알고 계실 것 같아 언급했습니다.

변경하려는 이유는 varchar보다 훨씬 적게 공간을 사용하기 때문에 공관 관리에 대한 이점이 있습니다.
또, 저희는 항상 query param 으로 runner_post를 호출하는데, 이때 필터링되는 것이 varchar 인 경우보다 enum 인 경우가 더 빠를겁니다.
단점도 있는데요. enum이 추가될때마다 마이그레이션을 해주어야하는데, 저는 enum이 추가되는 경우가 이제는 보이지 않아서요. 어떻게 생각하시나요?
supporter_runner_post 테이블 명 변경 -> supporter_appeal 어떻게 생각하시나요?

2023-09-10 12:05 UTC, shb03323 commented
테스트 터지는거 active profiles 설정때문에 그런데, 같이 해결해요

2023-09-11 07:32 UTC, hyena0608 reviewed
사소한 오타 정도만 커멘트 달았습니다~

2023-09-11 07:32 UTC, hyena0608 commented on backend/baton/src/main/java/touch/baton/domain/runnerpost/vo/CuriousContents.java
> +            throw new IllegalArgumentException("CuriousContents 객체 내부에 implementedContents 는 null 일 수 없습니다.");
```suggestion
            throw new IllegalArgumentException("CuriousContents 객체 내부에 curiousContents 는 null 일 수 없습니다.");
```

2023-09-11 07:32 UTC, hyena0608 commented on backend/baton/src/main/java/touch/baton/domain/runnerpost/vo/PostscriptContents.java
> +            throw new IllegalArgumentException("PostscriptContents 객체 내부에 implementedContents 는 null 일 수 없습니다.");
```suggestion
            throw new IllegalArgumentException("PostscriptContents 객체 내부에 postscriptContents 는 null 일 수 없습니다.");
```

2023-09-11 07:32 UTC, hyena0608 commented on backend/baton/src/test/java/touch/baton/domain/runnerpost/vo/CuriousContentsTest.java
> +public class CuriousContentsTest {
```suggestion
class CuriousContentsTest {
```

2023-09-11 07:32 UTC, hyena0608 commented on backend/baton/src/test/java/touch/baton/domain/runnerpost/vo/PostscriptContentsTest.java
> +public class PostscriptContentsTest {
```suggestion
class PostscriptContentsTest {
```

2023-09-12 08:37 UTC, cookienc requested changes
이거만 지워주세요!

2023-09-12 08:52 UTC, cookienc reviewed
LGTM!

2023-09-12 08:52 UTC, cookienc approved these changes

2023-09-12 08:58 UTC, hyena0608 approved these changes
굿굿 고생했어요!

2023-09-13 08:02 UTC, hyena0608 approved these changes
커멘트 반영까지 고생하셨어요!

2023-09-13 12:04 UTC, eunbii0213 approved these changes
LGTM!

2023-09-14 01:29 UTC, merged