태그 검색 API 구현
woowacourse-teams/2023-baton pull request #453
Opened 2023-09-10 23:58 UTC by eunbii0213

## 관련이슈

- resolved #446 

## 참고사항
태그 검색 API 구현입니다.

2023-09-11 06:46 UTC, hyena0608 requested changes
uri 수정 전에 미리 커멘트 조금(?) 달아뒀어요! 참고 부탁드립니다~

2023-09-11 06:46 UTC, hyena0608 commented on backend/baton/src/test/java/touch/baton/assure/runnerpost/RunnerPostReadAssuredTest.java
> +        tagRepository.save(TagFixture.create(new TagName("script")));
픽스처 사용해주셔도 좋을거 같습니다~
```suggestion
        tagRepository.save(TagFixture.create(TagNameFixture.tagName("java")));
        tagRepository.save(TagFixture.create(tagName("javascript")));
        tagRepository.save(TagFixture.create(tagName("script")));
```

2023-09-11 06:46 UTC, hyena0608 commented on backend/baton/src/test/java/touch/baton/assure/runnerpost/RunnerPostReadAssuredTest.java
> +        System.out.println(검색된_태그_목록.size());
```suggestion
```

2023-09-11 06:46 UTC, hyena0608 commented on backend/baton/src/test/java/touch/baton/assure/runnerpost/RunnerPostAssuredSupport.java
> +        public RunnerPostClientRequestBuilder 태그를_검색한다(final String 태그_이름) {
태그를 어떤 것으로 검색하는지 메서드명을 조금 더 자세하게 작성해주시면 좋을거 같아요~
물론 인자에 태그이름이 들어오니 현재 메서드로 괜찮다고 생각하시면 제 커멘트는 신경쓰지 않으셔도 좋아요.

2023-09-11 06:46 UTC, hyena0608 commented on backend/baton/src/test/java/touch/baton/config/RestdocsConfig.java
> +    protected TagRepository tagRepository;
TagRepository를 MockBean으로 등록하신 이유를 모르겠는데 혹시 설명해주실 수 있나요?

2023-09-11 06:46 UTC, hyena0608 commented on backend/baton/src/main/java/touch/baton/domain/tag/repository/TagRepository.java
> +    List<Tag> findTop10ByTagReducedNameValueContainingOrderByTagReducedNameValueAsc(String tagReducedName);
메서드를 이용해서 빠른 구현은 좋은거 같아요.
근데 메서드명이 너무 길어서 읽기 힘드네요 ㅠㅠ

2023-09-11 06:46 UTC, hyena0608 commented on backend/baton/src/main/java/touch/baton/domain/runnerpost/controller/response/TagSearchResponse.java
> +        public static TagResponse of(final Long id, final String name) {
Tag가 아닌 id, name를 받으신 이유가 있나요?

2023-09-11 06:46 UTC, hyena0608 commented on backend/baton/src/main/java/touch/baton/domain/runnerpost/controller/RunnerPostController.java
> +    public ResponseEntity<TagSearchResponses.Detail> readTags(@RequestParam String name) {
query parameter 명과 메서드명이 잘못되어 있는거 같아요.

2023-09-11 06:46 UTC, hyena0608 commented on backend/baton/src/main/java/touch/baton/domain/runnerpost/controller/RunnerPostController.java
> +        String reducedName = name.replaceAll(" ", "");
여기서 따로 replaceAll 메서드를 이용하신 이유가 뭔가요?

2023-09-11 06:46 UTC, hyena0608 commented on backend/baton/src/main/java/touch/baton/domain/runnerpost/controller/RunnerPostController.java
> +    }
final !! 웨얼 알 유

2023-09-11 06:46 UTC, hyena0608 commented on backend/baton/src/main/java/touch/baton/domain/runnerpost/controller/RunnerPostController.java
> +                .map(tag -> TagSearchResponse.TagResponse.of(tag.getId(), tag.getTagReducedName().getValue()))
응답을 할 때는 축약된 태그 이름을 반환해도 괜찮을까요? 🤔

2023-09-12 19:46 UTC, eunbii0213 commented on backend/baton/src/test/java/touch/baton/config/RestdocsConfig.java
> +    protected TagRepository tagRepository;
아이고 클래스에 넣었다고 생각했는데 RestDocsConfig에 넣었었군요... 제거했습니다!

2023-09-12 19:47 UTC, eunbii0213 commented on backend/baton/src/main/java/touch/baton/domain/tag/repository/TagRepository.java
> +    List<Tag> findTop10ByTagReducedNameValueContainingOrderByTagReducedNameValueAsc(String tagReducedName);
자동으로 생성해주는 기능을 이용하고자 하다보니 이런 네이밍을 쓸 수 밖에 없었던 것 같아요 🥲 어떻게 보면 자세해서 괜찮은 것 같기도하고.... 이건 다른 팀원들의 의견도 들어볼까요?!

2023-09-12 19:57 UTC, eunbii0213 commented on backend/baton/src/main/java/touch/baton/domain/runnerpost/controller/RunnerPostController.java
> +        String reducedName = name.replaceAll(" ", "");
ReducedName으로 태그를 찾기 때문입니다! 저번에 얘기했던 것 처럼 공백을 모두 제거한 값(reducedName)을 따로 저장했고, 이걸로 찾는다고 이해했습니다! 혹시 제가 잘못 이해한거라면 말씀해주세요~!

2023-09-12 19:57 UTC, eunbii0213 commented on backend/baton/src/main/java/touch/baton/domain/runnerpost/controller/RunnerPostController.java
> +    }
오마이갓! 쏘리 뽀이

2023-09-13 00:21 UTC, cookienc requested changes
고생하셨습니다! 
추가로 새로 만든 adoc 파일을 index.adoc 파일에 추가하셔야지 url로 접근 가능하니 추가해서 푸시해주세요

2023-09-13 01:15 UTC, hyena0608 commented on backend/baton/src/main/java/touch/baton/domain/runnerpost/controller/RunnerPostController.java
> +        String reducedName = name.replaceAll(" ", "");
TagReducedName VO를 이용하시면 어떤 의도를 갖는지 알기 더 쉬울거 같네요~

2023-09-13 01:18 UTC, hyena0608 commented on backend/baton/src/main/java/touch/baton/domain/runnerpost/controller/RunnerPostController.java
> +                .map(tag -> TagSearchResponse.TagResponse.of(tag.getId(), tag.getTagReducedName().getValue()))
1. 응답 내부 필드명이 tagName인데 축약된 태그 이름인지 헷갈리네요 ㅠㅠ
2. 현재 구현하신 태그 검색 기능을 이용하신다면 축약 태그 이름이 중복으로 나올거 같네요.

2023-09-13 01:20 UTC, hyena0608 commented on backend/baton/src/main/java/touch/baton/domain/tag/repository/TagRepository.java
> +    List<Tag> findTop10ByTagReducedNameValueContainingOrderByTagReducedNameValueAsc(String tagReducedName);
만약 사용하신다면 해당 기능에 대한 테스트를 작성해주시면 좋을거 같아요.
JPA에서 지원해주는 기능으로 믿음직 할 수 있겠지만 팀원분들이 메서드명을 읽고 기능을 파악하기가 어렵다고 느껴져요 🥲

2023-09-13 01:37 UTC, eunbii0213 commented on backend/baton/src/test/java/touch/baton/config/RestdocsConfig.java
> +import touch.baton.domain.tag.repository.TagRepository;
추가했다가 삭제했었는데 import문은 정리를 안 했군요...! 수정하겠습니다

2023-09-13 01:39 UTC, eunbii0213 commented on backend/baton/src/test/java/touch/baton/assure/runnerpost/RunnerPostAssuredSupport.java
> +
밑에 다른 메서드들도 이렇게 되어있어서 맞췄습니다!

2023-09-13 08:01 UTC, shb03323 commented on backend/baton/src/main/java/touch/baton/domain/tag/controller/TagController.java
> +        final String reducedName = TagReducedName.from(tagName).getValue();
TagReducedName은 VO이고 해당 객체를 controller에서 호출해서 service에 인자로 전달해주는 것이 어색한 것 같아요. 서비스 로직이라고 생각하거든요.

2023-09-13 08:04 UTC, shb03323 commented on backend/baton/src/main/java/touch/baton/domain/tag/controller/TagController.java
> +                .toList();
```suggestion
        final List<TagSearchResponse.TagResponse> tagSearchResponses = tagService.readTagsByReducedName(reducedName).stream()
                .map(TagSearchResponse.TagResponse::from)
                .toList();
```

2023-09-13 08:04 UTC, shb03323 commented on backend/baton/src/main/java/touch/baton/domain/tag/controller/TagController.java
> +                .toList();
이런 방법은 어떻게 생각하세요?

2023-09-13 08:05 UTC, shb03323 commented on backend/baton/src/main/java/touch/baton/domain/tag/controller/TagController.java
> +        final String reducedName = TagReducedName.from(tagName).getValue();
tagName을 서비스 인자로 보내서 reducedName으로 줄이는 작업을 service에서 처리하는 것은 어떻게 생각하시나요?

2023-09-13 08:13 UTC, shb03323 commented on backend/baton/src/main/java/touch/baton/domain/tag/repository/TagRepository.java
> +    List<Tag> findTop10ByTagReducedNameValueContainingOrderByTagReducedNameValueAsc(String tagReducedName);
저는 상관없다고 생각합니다. 저보다 JPA를 더 믿기 때문이죠!

2023-09-13 08:36 UTC, shb03323 commented on backend/baton/src/main/java/touch/baton/domain/tag/controller/response/TagSearchResponses.java
> +        }
정적 팩토리 메소드를 사용하는 이유가 무엇인가용?

2023-09-13 10:42 UTC, shb03323 commented on backend/baton/src/main/java/touch/baton/domain/tag/repository/TagRepository.java
> +    List<Tag> findTop10ByTagReducedNameValueContainingOrderByTagReducedNameValueAsc(String tagReducedName);
하지만 containing 방식이 조금 걸리네요. 저희는 첫 글자 기준으로 검색합니다!

2023-09-13 10:45 UTC, shb03323 commented on backend/baton/src/test/java/touch/baton/assure/runnerpost/RunnerPostAssuredSupport.java
> +
maybe 다른 분들 실수일 가능성 농후합니다! 아무 내용도 없는 경우에는 개행이 없는 것이 자연스러운 것 같아요!
https://google.github.io/styleguide/javaguide.html#s4.1.3-braces-empty-blocks

2023-09-13 10:47 UTC, shb03323 commented on backend/baton/src/test/java/touch/baton/assure/tag/TagAssuredSupport.java
> +        public TagAssuredSupport.TagClientRequestBuilder 태그를_이름으로_오름차순일때_10개_검색한다(final String 태그_이름) {
태그_이름을_오름차순으로_10개_검색한다

2023-09-13 10:49 UTC, shb03323 commented on backend/baton/src/test/java/touch/baton/assure/tag/TagAssuredSupport.java
> +        public TagAssuredSupport.TagClientRequestBuilder 태그를_이름으로_오름차순일때_10개_검색한다(final String 태그_이름) {
이런 메소드명은 어떠세요?
중요한 것은 태그 이름을 검색하는 것인데, 조사때문에 모호하게 표현되어 있는 듯한 느낌이 들어서요.

2023-09-13 10:50 UTC, shb03323 commented on backend/baton/src/test/java/touch/baton/assure/tag/TagAssuredSupport.java
> +
이곳 개행이 있습니다!

2023-09-13 10:54 UTC, shb03323 commented on backend/baton/src/test/java/touch/baton/assure/tag/TagReadAssuredTest.java
> +                );
한줄로 하는 거 다들 어떻게 생각하시나요?

2023-09-13 10:58 UTC, shb03323 commented on backend/baton/src/test/java/touch/baton/document/tag/read/TagReadApiTest.java
> +                        .accept(APPLICATION_JSON)
accept를 추가하신 이유가 궁금합니다!

2023-09-14 01:25 UTC, eunbii0213 commented on backend/baton/src/main/java/touch/baton/domain/tag/controller/TagController.java
> +        final String reducedName = TagReducedName.from(tagName).getValue();
좋습니다!! 반영할게요 ㅎㅎ

2023-09-14 01:25 UTC, eunbii0213 commented on backend/baton/src/main/java/touch/baton/domain/tag/controller/TagController.java
> +                .toList();
조아요!!!

2023-09-14 01:26 UTC, eunbii0213 commented on backend/baton/src/main/java/touch/baton/domain/tag/controller/response/TagSearchResponses.java
> +        }
다른 곳(Ex. RunnerPostReadResponses)에서도 정적 팩토리에서도 사용하고 있기 때문에 통일성을 맞추기 위함이었습니다!

2023-09-14 01:27 UTC, eunbii0213 commented on backend/baton/src/test/java/touch/baton/assure/tag/TagAssuredSupport.java
> +        public TagAssuredSupport.TagClientRequestBuilder 태그를_이름으로_오름차순일때_10개_검색한다(final String 태그_이름) {
오 안 그래도 저 메서드명 찝찝했는데 저 네이밍이 훨씬 맘에 들어요! 감사합니다~~

2023-09-14 01:29 UTC, eunbii0213 commented on backend/baton/src/test/java/touch/baton/assure/tag/TagReadAssuredTest.java
> +                );
다른 부분들도 이렇게 되어있어서 통일성 맞추고자 한거였는데 그럼 다 바뀌게 될 것 같긴해용

2023-09-14 01:37 UTC, shb03323 commented on backend/baton/src/test/java/touch/baton/assure/tag/TagReadAssuredTest.java
> +                );
고러면 그냥 내비두는 것이 좋을것 같네요 굿굿

2023-09-14 02:06 UTC, eunbii0213 commented on backend/baton/src/main/java/touch/baton/domain/tag/controller/response/TagSearchResponses.java
> +        }
그 RunnerPostReadResponses뿐만이 아니라 거의 다 그렇게 쓰고 있는데 그럼 이것들도 다 바꿔야하지 않을까요??

2023-09-14 02:07 UTC, eunbii0213 commented on backend/baton/src/main/java/touch/baton/domain/tag/controller/response/TagSearchResponses.java
> +        }
정적 팩토리 메소드가 아닌 일반 생성자 메소드를 사용해야하는 이유가 무엇인가요?ㅅ?

2023-09-14 05:05 UTC, shb03323 commented on backend/baton/src/main/java/touch/baton/domain/tag/controller/response/TagSearchResponses.java
> +        }
정적 팩토리 메소드는 일반 생성자만으로 표현하기 어려운, 혹은 생성 작업 말고 추가 작업이 있는 경우 사용을 권장하고 있습니다. 
지금의 경우 일반 생성자 메소드를 사용하는 것이 더 자연스럽다고 생각해요. 정팩메를 쓰는 순간 추가적인 다른 작업이 있나? 하고 생각하게 되는 것 같아서요.

2023-09-14 05:06 UTC, shb03323 commented on backend/baton/src/main/java/touch/baton/domain/tag/repository/TagRepository.java
> +            """)
좋아요!

2023-09-14 05:21 UTC, cookienc requested changes
🏃🏃🏃💨

2023-09-14 05:21 UTC, cookienc commented on backend/baton/src/main/java/touch/baton/domain/tag/service/TagService.java
> +        final String reducedName = TagReducedName.from(tagName).getValue();
getValue()로 값을 안빼고 그냥 넣어도 검색 되지 않나요?

2023-09-14 05:21 UTC, cookienc commented on backend/baton/src/test/java/touch/baton/domain/tag/service/TagServiceReadTest.java
> +
repo 테스트에서는 for문인데 여기서는 instream이네요. 사용하시는 기준이 있나요? 
\+ repo 코멘트와 같습니다

2023-09-14 05:21 UTC, cookienc commented on backend/baton/src/main/java/touch/baton/domain/tag/controller/response/TagSearchResponse.java
> +            return new TagResponse(tag.getId(), tag.getTagReducedName().getValue());
tagName으로 바꿔주세요

2023-09-14 05:23 UTC, shb03323 commented on backend/baton/src/main/java/touch/baton/domain/tag/controller/response/TagSearchResponse.java
> +            return new TagResponse(tag.getId(), tag.getTagReducedName().getValue());
reducedName이 아니라 name 입니당

2023-09-14 05:23 UTC, shb03323 requested changes
조금만 수정하면 될 것 같아요

2023-09-14 05:24 UTC, hyena0608 requested changes
반복해서 놓치시는 부분들을 주의해주세요!
화이팅입니다~

2023-09-14 05:24 UTC, hyena0608 commented on backend/baton/src/main/java/touch/baton/domain/tag/repository/TagRepository.java
>  }
사소한거지만 소문자로 변경 부탁드려요!

2023-09-14 05:24 UTC, hyena0608 commented on backend/baton/src/main/java/touch/baton/domain/tag/service/TagService.java
> +    }
TagReducedName을 넘기지 않은 이유가 있나요?

2023-09-14 05:24 UTC, hyena0608 commented on backend/baton/src/test/java/touch/baton/assure/tag/TagAssuredSupport.java
> +}
Support인데 api를 요청하는게 맞을까요?

2023-09-14 05:24 UTC, hyena0608 commented on backend/baton/src/test/java/touch/baton/document/tag/read/TagReadApiTest.java
> +    void readTags() throws Exception {
테스트 메서드명이지만 좀 더 명확하게 표현해주시면 좋을거 같아요

2023-09-14 05:24 UTC, hyena0608 commented on backend/baton/src/test/java/touch/baton/domain/tag/repository/TagRepositoryReadTest.java
> +    }
저희 EntityManager 이용하기로 결정했었는데!!

2023-09-14 05:24 UTC, hyena0608 commented on backend/baton/src/test/java/touch/baton/domain/tag/repository/TagRepositoryReadTest.java
> +        }
살짝 생각해야 의도를 알 수 있는거 같네요

2023-09-14 05:24 UTC, hyena0608 commented on backend/baton/src/test/java/touch/baton/domain/tag/repository/TagRepositoryReadTest.java
> +        });
인덱스 0에 java1이 있고 인덱스 9에 java18이 있는지 확인하기 위해서는 위에서 작성하신 for문을 읽고 하나하나 생각해야지 해당 테스트에 대해서 성공한다고 생각할 수 있는 로직이네요..ㅠ

2023-09-14 05:24 UTC, hyena0608 commented on backend/baton/src/test/java/touch/baton/domain/tag/repository/TagRepositoryReadTest.java
> +                .forEach(tag -> tagRepository.save(tag));
🤔

2023-09-14 05:24 UTC, hyena0608 commented on backend/baton/src/test/java/touch/baton/domain/tag/repository/TagRepositoryReadTest.java
> +class TagRepositoryReadTest extends RepositoryTestConfig {
테스트 클래스명은 Read로 수정해주셨는데 TagRepository는 변경하지 않으신 이유가 있나요?

2023-09-14 05:24 UTC, hyena0608 commented on backend/baton/src/test/java/touch/baton/domain/tag/service/TagServiceReadTest.java
> +public class TagServiceReadTest extends ServiceTestConfig {
자동 완성!

2023-09-14 05:24 UTC, hyena0608 commented on backend/baton/src/test/java/touch/baton/domain/tag/service/TagServiceReadTest.java
> +
🤔

2023-09-14 06:34 UTC, eunbii0213 commented on backend/baton/src/main/java/touch/baton/domain/tag/service/TagService.java
> +        final String reducedName = TagReducedName.from(tagName).getValue();
혹시 왜인지 알려주실 수 있을까요?? tagName의 value값으로 검색해야 하는 것 아니었나요! 그래서 .getValue()를 하구 parameter를 String으로 해서 넘겨준 거였는데! reducedName 객체로 냅다 넘겨줘도 되나요?ㅅ?

2023-09-14 06:35 UTC, eunbii0213 commented on backend/baton/src/test/java/touch/baton/domain/tag/service/TagServiceReadTest.java
> +
아이고 처음에는 for문으로 작성했었는데, intstream으로 바꾸는 과정에서 하나를 빼먹었나보네요 ㅎㅎ; 죄송합니다

2023-09-14 06:37 UTC, eunbii0213 commented on backend/baton/src/main/java/touch/baton/domain/tag/controller/response/TagSearchResponse.java
> +            return new TagResponse(tag.getId(), tag.getTagReducedName().getValue());
에고고;; 제가 진짜 정신이 없네요 죄송해요

2023-09-14 06:37 UTC, eunbii0213 commented on backend/baton/src/main/java/touch/baton/domain/tag/controller/response/TagSearchResponse.java
> +            return new TagResponse(tag.getId(), tag.getTagReducedName().getValue());
맞아요 ㅜㅜ 제가 진짜 정신이 없네요; 죄송합니다

2023-09-14 06:40 UTC, eunbii0213 commented on backend/baton/src/main/java/touch/baton/domain/tag/repository/TagRepository.java
>  }
넵!! 감사합니닷!!

2023-09-14 07:02 UTC, eunbii0213 commented on backend/baton/src/test/java/touch/baton/document/tag/read/TagReadApiTest.java
> +    void readTags() throws Exception {
어우 초반에 작성한 메서드 명인데 메서드 명 바뀐 걸 반영을 안 했군요.. 반영했슴다!

2023-09-14 07:02 UTC, eunbii0213 commented on backend/baton/src/test/java/touch/baton/assure/tag/TagAssuredSupport.java
> +}
ㅋㅋㅋ... 저 진짜 정신 나간 것 같군요 죄송합니다;ㅠ

2023-09-14 07:05 UTC, eunbii0213 commented on backend/baton/src/test/java/touch/baton/domain/tag/repository/TagRepositoryReadTest.java
> +    }
안녕하세요? 바보입니다. 잘 부탁드립니다...

2023-09-14 07:44 UTC, eunbii0213 commented on backend/baton/src/test/java/touch/baton/domain/tag/repository/TagRepositoryReadTest.java
> +class TagRepositoryReadTest extends RepositoryTestConfig {
전 바보입니다. 이렇게 바보같은 저라도 괜찮으시겠어요?

2023-09-14 07:53 UTC, eunbii0213 commented on backend/baton/src/test/java/touch/baton/domain/tag/service/TagServiceReadTest.java
> +
냅다.. persist 무지성 와라락 해버렸습니다... 괜찮으신가요..~!

2023-09-14 09:22 UTC, shb03323 commented on backend/baton/src/test/java/touch/baton/assure/tag/TagAssuredSupport.java
> +
🥲

2023-09-14 09:22 UTC, shb03323 commented on backend/baton/src/test/java/touch/baton/assure/tag/TagAssuredSupport.java
> +
개행 🥲

2023-09-14 09:26 UTC, shb03323 commented on backend/baton/src/test/java/touch/baton/assure/tag/TagReadAssuredTest.java
> +    public static void 러너_게시글_생성을_성공한다(final String 사용자_액세스_토큰, final List<String> 태그_목록) {
🥲 함수 추출 실수

2023-09-14 09:28 UTC, shb03323 approved these changes
고생하셨습니다.

2023-09-14 09:28 UTC, hyena0608 approved these changes

2023-09-14 09:28 UTC, cookienc approved these changes

2023-09-14 11:17 UTC, merged