미션 레포에 브랜치 생성 기능 구현
woowacourse-teams/2023-baton pull request #455
Opened 2023-09-11 08:59 UTC by shb03323

## 관련이슈

- resolved #452 

## 참고사항
목 테스트만 했어용

2023-09-12 08:51 UTC, cookienc requested changes
고쳐주세용!

2023-09-12 08:51 UTC, cookienc commented on backend/baton/src/main/java/touch/baton/domain/member/controller/MemberBranchController.java
> +    ResponseEntity<Void> createMemberBranch(@AuthMemberPrincipal final Member member,
public 붙이는게 어떨까요?

2023-09-12 08:51 UTC, cookienc commented on backend/baton/src/main/java/touch/baton/domain/oauth/controller/OauthController.java
> +        System.out.println(jwtToken);
sout 지워주세요

2023-09-12 08:51 UTC, cookienc commented on backend/baton/src/main/java/touch/baton/infra/github/request/CreateBranchRequest.java
> +public record CreateBranchRequest(String ref, String sha) {
ref 와 sha 는 github api 명세인가요?

2023-09-12 08:51 UTC, cookienc commented on backend/baton/src/main/java/touch/baton/infra/github/GithubBranchService.java
> +        if (Objects.requireNonNull(response.getBody()).contains(DUPLICATED_BRANCH_ERROR_MESSAGE)) {
.

2023-09-12 08:51 UTC, cookienc commented on backend/baton/src/test/java/touch/baton/assure/member/MemberBranchAssuredSupport.java
> +public class MemberBranchAssuredSupport {
public!

2023-09-12 08:51 UTC, cookienc commented on backend/baton/src/test/java/touch/baton/assure/member/MemberBranchCreateAssuredTest.java
> +public class MemberBranchCreateAssuredTest extends AssuredTestConfig {
public 222!

2023-09-12 08:51 UTC, cookienc commented on backend/baton/src/test/java/touch/baton/document/github/GithubBranchApiTest.java
> +public class GithubBranchApiTest extends RestdocsConfig {
public!

2023-09-12 08:51 UTC, hyena0608 reviewed
커멘트 조금 남겼어요! 👍

2023-09-12 08:51 UTC, hyena0608 commented on backend/baton/src/main/java/touch/baton/domain/oauth/controller/OauthController.java
> +        System.out.println(jwtToken);
```suggestion
```

2023-09-12 08:51 UTC, hyena0608 commented on backend/baton/src/main/java/touch/baton/infra/github/GithubBranchService.java
> +
```suggestion

```

2023-09-12 08:51 UTC, hyena0608 commented on backend/baton/src/main/java/touch/baton/infra/exception/InfraException.java
> +public class InfraException extends BaseException {
외부에 의존되는 부분에서 발생할 수 있는 예외를 더 정확하게 잡을 수 있으니 좋네요!!
이후에 다른 외부 예외가 더 추가될 수 있을거 같은데 예외 메시지를 해당 클래스 내부에서 직접 정의하거나 혹은
각 플랫폼에 따른 예외를 구현해서 사용하는 편도 좋을거 같아요

2023-09-12 08:51 UTC, hyena0608 commented on backend/baton/src/main/java/touch/baton/infra/github/GithubBranchService.java
> +    }
HttpStatus를 확인한 후 바로 return 하는 것보다 응답을 먼저 확인한 후에 HttpStatus를 확인하는 편이 더 정확할거 같다는 생각입니다!

2023-09-12 08:54 UTC, shb03323 commented on backend/baton/src/main/java/touch/baton/infra/exception/InfraException.java
> +public class InfraException extends BaseException {
오 그 방법이 더 좋아보여요. 수정하겠습니다.

2023-09-12 08:55 UTC, shb03323 commented on backend/baton/src/main/java/touch/baton/infra/github/GithubBranchService.java
> +import org.springframework.web.client.RestTemplate;
사용해보려했는데, 매개변수를 설정하는 부분이 불편하더라구요. 매개변수 설정하는 방법 알고 계시다면 같이 이야기해요.

2023-09-12 08:56 UTC, shb03323 commented on backend/baton/src/main/java/touch/baton/infra/github/request/CreateBranchRequest.java
> +public record CreateBranchRequest(String ref, String sha) {
옙 그렇습니다

2023-09-12 08:57 UTC, hyena0608 commented on backend/baton/src/main/java/touch/baton/infra/github/GithubBranchService.java
> +public class GithubBranchService {
Service라는 네이밍을 수정해도 좋을거 같아요.
저희가 내부에서 사용하는 비즈니스 로직을 수행하는 서비스 계층과는 달리 외부 기능을 호출하기만 하는 거 같아요.
또한 트랜잭션이 필요없는 부분인거 같은데 @Service가 아닌 @Component를 이용하고 GithubBranchManager, GithubBranchCreator 등으로 하시는거는 어떠신가요?

2023-09-12 10:46 UTC, shb03323 commented on backend/baton/src/main/java/touch/baton/infra/github/GithubBranchService.java
> +public class GithubBranchService {
오오 너무 좋은 생각입니다. 바로 진행하겠습니다.

2023-09-12 13:45 UTC, shb03323 commented on backend/baton/src/main/java/touch/baton/infra/github/GithubBranchService.java
> +    }
깃허브 docs에서 201 아니면 422 2가지로 status를 주고 있는데요. 422가 아닌 경우는 무조건 성공이기 때문에 저렇게 설정을 했었습니다. 제 생각이 짧았네요. 너무 제 위주로만 생각했었습니다. 이해가 쉽지 않은 코드였군요. 말씀해주셔서 감사합니다.

2023-09-12 13:53 UTC, shb03323 commented on backend/baton/src/main/java/touch/baton/infra/github/GithubBranchService.java
> +    }
응답을 확인한다는 말씀이 확 와닿지 않는데, 조금 더 자세히 말씀해주실 수 있을까요? 의도와 다르게 된 것 같기도 해서요.
```java
if (response.getStatusCode() == HttpStatus.CREATED) {
            return;
        }
```
이렇게 설정했는데, 응답 확인에 대한 부분은 확실히 이해하지는 못한 것 같아서요.

2023-09-12 13:58 UTC, shb03323 commented on backend/baton/src/test/java/touch/baton/document/github/GithubBranchApiTest.java
> +
RestAssured 만을 위해 config를 만들었었어요. 인수테스트인데 어쩔 수 없이 mock으로 등록한거였는데요. docs 테스트는 mock 테스트이기 때문에 mock한 것을 대놓고 보여주기 위해 어노테이션을 이용해 등록했습니다. 그리고 MockGithubBranchServiceConfig는 GithubApiTest 시에 주입되지 않더라구용

2023-09-12 13:58 UTC, shb03323 commented on backend/baton/src/main/java/touch/baton/infra/github/GithubBranchService.java
> +public class GithubBranchService {
오오오오 너무 좋아요

2023-09-13 00:22 UTC, cookienc requested changes
index.adoc에도 추가해주세요~

2023-09-13 08:06 UTC, hyena0608 approved these changes
Exception 예외 반환 쪽 커멘트 하나 남겼습니다! 굿

2023-09-13 08:06 UTC, hyena0608 commented on backend/baton/src/main/java/touch/baton/domain/common/GlobalControllerAdvice.java
> +        return ResponseEntity.internalServerError().body(ServerErrorResponse.from(ex));
내부 예외 메시지는 외부로 반환하지 않는거는 어떤가요?

2023-09-13 08:09 UTC, cookienc approved these changes
LGTM!

2023-09-13 08:56 UTC, cookienc approved these changes

2023-09-13 08:56 UTC, cookienc approved these changes
수고하셨습니다.

2023-09-13 12:14 UTC, eunbii0213 approved these changes

2023-09-13 12:14 UTC, eunbii0213 submitted a review, later dismissed
후덜덜 천재다

2023-09-14 08:13 UTC, merged