최종 페이지네이션
woowacourse-teams/2023-baton pull request #611
Opened 2023-09-29 14:22 UTC by shb03323

## 관련이슈

- resolved #610 

## 참고사항
변경 사항이 많아 보기 힘들 것 같아요.
정리해보자면

### 기존 service가 응답 객체 만들었던 거 respose dto가 응답 객체 만들기
응답을 dto에서 합치려다보니 단점도 나타나더라구요.
```java
public static <T> PageResponse<T> of(final List<RunnerPost> runnerPosts,
                                         final Function<RunnerPost, T> mapper, // 요기
                                         final int limit) {
        final List<T> data = runnerPosts.stream()
                .map(mapper)
                .toList();
        final PageInfo pageInfo = PageInfo.from(limit, data.size());
        if (pageInfo.isLast) {
            return new PageResponse<>(data, pageInfo);
        }
        return new PageResponse<>(data.subList(0, limit), pageInfo);
    }
``` 
저 부분 어쩔 수 없이 함수형 인터페이스 쓰게 되었는데 어떻게 생각하시나요? 여기에서 보면 예쁘게 보이지만 `PageResponse` 객체 생성하는 부분에서는 아래와 같이 가독성이 조금 떨어져요.
```java
return PageResponse.of(
                runnerPosts,
                runnerPost -> RunnerPostResponse.SimpleByRunner.of(runnerPost, runnerPostsApplicantCount.getApplicantCountById(runnerPost.getId()), runnerPostTags),
                pageParams.limit()
        );
```
다른 좋은 방법 없을까요?

### /profile/runner, /profile/runner/{runnerId}
저 api 안쓰이는 것 같은데 명세서 상으로는 아직 삭제하지 않아서요. 삭제할까용?

### 테스트의 도메인 패키지
우리 3몹 플레이 할 때 저거 패키지 신경 못 써서 패키징 이상하게 되어서 수정했음

### 서포터로 게시글 페이징 응답
러너가 보여야한다고 생각해서 러너 넣었는데 어떻게 생각? 나중에 프론트랑 이야기하긴 할거임.

### 테스트에서 serviceConfig, repositoryConfig
여기에 `RunnerPostPageRepository` 자동 주입하게 만들고 싶은데, 어떻게 해야하지...

---

레거시 조금 더 수정하려 했는데 다 수정하려다가 큰코 다칠 것 같아서 어느정도 합리화 했어요.

2023-10-04 03:02 UTC, hyena0608 reviewed
✨디투✨ 고생하셨어요!

커멘트 몇 개 달았는데 만약 수정하게 된다면 변경할게 많아져서 혹시나 적용하신다면 이후에 다시 한 번 더 커멘트 달도록 하겠습니다!

2023-10-04 03:22 UTC, hyena0608 reviewed
pr에 남기신 내용 중 Querydsl Test 관한 내용입니다!

2023-10-04 03:22 UTC, hyena0608 commented on backend/baton/src/test/java/touch/baton/config/RepositoryTestConfig.java
> +
QuerydslRepositoryTestConfig를 만드는거는 어떤가요?

테스트용 Querydsl 관련한 거를 한 곳에서 관리하기 위해서 프로덕션에 있는 QuerydslConfig를 이용하지 않았습니다.

그리고 아래와 같이 QuerydslRepositoryTestConfig를 만들었습니다.

구현한 Config를 RepositoryTestConfig에서 import 받아 사용하면 될 거 같습니다.

이제 테스트에서 `@Autowired`로 RunnerPostPageRepository를 주입 받을 수 있습니다.

테스트 통과하는거 확인했습니다!

```java
@TestConfiguration
public class QuerydslRepositoryTestConfig {

    @PersistenceContext
    private EntityManager em;

    @Bean
    JPAQueryFactory jpaQueryFactory() {
        return new JPAQueryFactory(em);
    }

    @Bean
    RunnerPostPageRepository runnerPostPageRepository() {
        return new RunnerPostPageRepository(jpaQueryFactory());
    }
}
```

```java
@Import({JpaConfig.class, QuerydslRepositoryTestConfig.class})
@DataJpaTest
public abstract class RepositoryTestConfig {
}
```

```java
class RunnerPostPageRepositoryTest extends RepositoryTestConfig {

    @Autowired
    private RunnerPostPageRepository runnerPostPageRepository;

}
```

![image](https://github.com/woowacourse-teams/2023-baton/assets/82203978/ce7e4f4c-2e95-4cca-bbd3-e40238dfe736)

2023-10-04 07:01 UTC, cookienc requested changes
±3000!! 고생했습니다 디투~ 리뷰 확인해주세요

2023-10-05 05:44 UTC, shb03323 commented on backend/baton/src/main/java/touch/baton/domain/runnerpost/query/service/RunnerPostQueryService.java
> +    }
페이지 리스폰스 방식 조금 변경했습니다.

2023-10-05 05:46 UTC, shb03323 commented on backend/baton/src/main/java/touch/baton/domain/runnerpost/query/service/dto/PageParams.java
> +public record PageParams(Long cursor, @ValidNotNull(clientErrorCode = INVALID_QUERY_STRING_FORMAT) Integer limit) {
좋아요

2023-10-05 05:52 UTC, shb03323 commented on backend/baton/src/main/java/touch/baton/domain/runnerpost/query/service/RunnerPostQueryService.java
> +        final int queryCount = pageParams.limit() + ADDITIONAL_QUERY_DATA_COUNT;
오 좋은 아이디어에요!!!!

2023-10-05 06:08 UTC, shb03323 commented on backend/baton/src/test/java/touch/baton/config/RepositoryTestConfig.java
> +
크으 감사합니다.

2023-10-05 06:09 UTC, shb03323 commented on backend/baton/src/main/java/touch/baton/domain/common/response/PageResponse.java
> +        return new PageResponse<>(data.subList(0, limit), pageInfo);
적용 완료

2023-10-05 06:11 UTC, shb03323 commented on backend/baton/src/test/java/touch/baton/document/runnerpost/read/RunnerPostReadWithLoginedSupporterApiTest.java
> +        given(spyLoginedSupporter.getId()).willReturn(1L);
오 좋아요. 알려주셔서 감사합니다.

2023-10-05 06:14 UTC, shb03323 commented on backend/baton/src/test/java/touch/baton/domain/runnerpost/query/repository/RunnerPostPageRepositoryTest.java
> +        final List<RunnerPost> runnerPosts = runnerPostPageRepository.pageByReviewStatusAndTagReducedName(previousLastId, limit, null, null);
예리하네요. 굿

2023-10-05 07:10 UTC, cookienc reviewed
고고

2023-10-05 08:47 UTC, hyena0608 approved these changes
굿굿 페이지네이션 고생하셨어요

2023-10-05 08:57 UTC, merged