react query 마이그레이션
woowacourse-teams/2023-baton pull request #612
Opened 2023-10-02 10:02 UTC by tkdrb12

## 관련이슈

- resolved #599

## 참고사항
- [x] 메인페이지 페이지네이션 방식 변경
- [x] 에러 핸들링 방식 변경 ( fetch메서드에서 에러를 throw하고 react-query hook이 에러 토스트 메세지를 생성)
- [x] useLogin을 제외한 api fetch 방식 변경 (useFetch를 사용하지 않고, apis 폴더내의 미리 url을 정의해놓은 api함수 사용) 

## query
- 페이지네이션이 존재 -> useInfiniteQuery 사용
- post, patch, delete api -> useMutation 사용
- api에서 받아온 값이 state값을 초기화 할 때, -> useSuspenseQuery 사용 
- 기타 -> useQuery 사용

2023-10-04 07:40 UTC, guridaek requested changes
고생 많았어요 도리!
추상화 잘 된 것 같고 읽기 좋게 잘 짠 것 같아요.
주로 질문이 많아요,, 리뷰 확인 부탁합니다!

2023-10-04 07:40 UTC, guridaek commented on frontend/src/components/RunnerPost/RunnerPostSearchBox/RunnerPostSearchBox.tsx
> +  fetchNextPage: () => void;
얘는 Props에서 빼도 될 것 같네요!

2023-10-04 07:40 UTC, guridaek commented on frontend/src/hooks/query/useReviewComplete.ts
> +      queryClient.refetchQueries({ queryKey: ['mySupporterPost', 'DONE'] });
refetch, invalidate 덕에 마이 페이지 게시글 상태 걱정을 덜 해도 되겠네요 👍
`refetchQueries` 와 `invalidateQueries` 는 어떤 기준으로 나눈건가요?

2023-10-04 09:48 UTC, gyeongza reviewed
추석 연휴동안 너무 고생 많았어요 도리 
확실히 리액트 쿼리 도입하니 컴포넌트 내부 코드 양이 많이 줄어드네요 👍 (좀 알려주세요 ㅎㅎ)
로컬에서 테스트 해보니 문제는 없는 것 같습니다.

몇개 궁금한 코멘트만 남겨놓겠습니다 ~

2023-10-04 09:48 UTC, gyeongza commented on frontend/src/apis/fetch.ts
> +};
fetchApi가 이미 promise를 반환하고 있는데 여기서 async를 사용한 이유가 궁금해요

2023-10-04 09:48 UTC, gyeongza commented on frontend/src/hooks/query/useProposedSupporterList.ts
> +    queryFn: async () => getProposedSupporterList(runnerPostId).then((res) => res.data),
여기서는 then이 필요하겠군요

2023-10-04 09:48 UTC, gyeongza commented on frontend/src/hooks/query/useRunnerPostList.ts
> +export const useRunnerPostList = (reviewStatus?: ReviewStatus, tagName?: string) => {
![스크린샷 2023-10-04 오후 6 47 35](https://github.com/woowacourse-teams/2023-baton/assets/62369936/0d5ce281-395d-403d-b8f6-e0ed3a6a768e)

(궁금한점) ReviewStatus가 바뀔 때마다 새로 요청을 보내는데 캐싱해놓을 수 있는 방법이 있나요??

2023-10-05 01:43 UTC, tkdrb12 commented on frontend/src/apis/fetch.ts
> +    .catch(() => throwErrorBadRequest());
에러 처리를 다음과 같이 분리하려고 코드를 작성했습니다
1. 네트워크 문제가 발생하거나  api url 입력이 잘못되어 api 요청 자체가 실패할 경우 => throwErrorBadRequest 에서 에러 발생
2. api 응답은 있지만 json이 유효하지 않은 경우 => validateJson 에서 에러 발생

설계한대로 동작하려면 catch와 then의 순서를 바꿔서 작성할 필요가 있었네요

2023-10-05 03:10 UTC, tkdrb12 commented on frontend/src/apis/apis.ts
> +  return request.get<GetSupporterCandidateResponse>(`/posts/runner/${runnerPostId}/supporters`, true);
제거했습니다

2023-10-05 03:10 UTC, tkdrb12 commented on frontend/src/hooks/query/useFeedbackToSupporter.ts
> +    },
mutaion 사용시 response 응답 값이 정상인데도 json 값이 존재하지 않으면 화면이 멈추는 문제가 있어 동기적으로 코드가 동작하도록 아래와 같이 코드를 수정했었습니다. 

현재 두가지 오류사항 모두 수정했습니다

2023-10-05 03:11 UTC, tkdrb12 commented on frontend/src/hooks/query/useMyGithubUrl.ts
> +    },
수정했습니다

2023-10-05 03:21 UTC, tkdrb12 commented on frontend/src/hooks/query/useReviewComplete.ts
> +      queryClient.refetchQueries({ queryKey: ['mySupporterPost', 'DONE'] });
컴포넌트가 마운트 되는 과정 없이 즉시 데이터 업데이트 가 필요할 시 -> refetch
컴포넌트가 페이지 이동이나 버튼 클릭 등으로 인해 데이터 refresh가 되는 컴포넌트의 리렌더링이 필연적으로 발생할 시 -> invalidate
최대한 데이터 fetch가 덜 되는 방향으로 설정했습니다

근데 현재 staletime을 따로 설정하지 않아 invalidate는 동작하지 않고 있을겁니다

2023-10-05 03:23 UTC, tkdrb12 commented on frontend/src/App.tsx
> +          <Suspense fallback={<div></div>}>
추가했습니다

2023-10-05 03:34 UTC, tkdrb12 commented on frontend/src/hooks/query/useMyPostList.ts
> +    },
파라미터 값을 넘겨줄 경우 인자가 없을 때 undefined 값으로 처리되니 이 경우에는 null값 보다는 undefined값으로 사용하는 게 더 적절한 것 같습니다.

2023-10-05 03:36 UTC, tkdrb12 commented on frontend/src/hooks/query/useMyPostList.ts
> +    },
then은 테스트용 코드였는데 아직 제거가 안됐었습니다.

```
 queryFn: ({ pageParam }) => {
      return isRunner
        ? getMyRunnerPost(PAGE_SIZE, pageParam, reviewStatus)
        : getMySupporterPost(PAGE_SIZE, pageParam, reviewStatus);
    },
```

개인적으로 중괄호가 없으면 읽기 불편한 것 같아 추가로 중괄호를 씌워 반영했습니다

2023-10-05 03:38 UTC, tkdrb12 commented on frontend/src/components/RunnerPost/RunnerPostSearchBox/RunnerPostSearchBox.tsx
> +  fetchNextPage: () => void;
반영했습니다

2023-10-05 03:40 UTC, tkdrb12 commented on frontend/src/hooks/query/useRunnerPostList.ts
> +    queryFn: ({ pageParam }) => getRunnerPost(PAGE_LIMIT, reviewStatus, pageParam, tagName).then((res) => res),
`네트워크 문제가 발생하거나 api url 입력이 잘못되어 api 요청 자체가 실패할 경우`와
`api 응답은 있지만 json이 유효하지 않은 경우` 에러 처리 케이스를 분리하기 위해 다음과 같이 코드를 작성했습니다

2023-10-05 03:47 UTC, tkdrb12 commented on frontend/src/hooks/query/useRunnerPostList.ts
> +    data: queryResult.data as NonNullable<typeof queryResult.data>,
suspenseQuery를 도입했다 가정하고 코드를 작성했기 때문입니다.

아직 로딩 UI가 없고 컴포넌트 분할이 이뤄지지 않아서 suspenseQuery로 작성하지 않아
현재 data값에는 undefined값이 들어오기도 합니다.
따라서 suspense를 도입하지 않는다면 NonNullable 타입을 제거하는 게 맞습니다

2023-10-05 03:51 UTC, tkdrb12 commented on frontend/src/apis/fetch.ts
> +};
따로 의미는 없고 명시적으로 비동기 함수라는 걸 드러내고 싶었기 때문입니다.
api 함수에 사용한 async와 함께 제거했습니다

2023-10-05 03:54 UTC, tkdrb12 commented on frontend/src/hooks/query/useRunnerPostList.ts
> +export const useRunnerPostList = (reviewStatus?: ReviewStatus, tagName?: string) => {
queryClient에 전역으로 staleTime을 설정해놓으면 됩니다.
현재 push한 코드에 staleTime을 1분으로 설정해놓아 1분 동안 캐싱처리 될 겁니다.

2023-10-05 05:11 UTC, guridaek requested changes

2023-10-05 05:11 UTC, guridaek commented on frontend/src/hooks/query/useFeedbackToSupporter.ts
> +    },
```suggestion
    mutationFn: async (formData: PostFeedbackRequest) => {
      await postFeedbackToSupporter(formData);
    },
```
지금도 에러가 안잡히는 것 같아요. 일단 성공 이후, 비동기 함수 안에서 에러가 던져지는 것 같아요
async를 붙일거면 위처럼 await을 붙여주거나 아래 `useMissionBranchCreation`에서처럼 함수를 바로 리턴해줘야 에러가 잡히는 것 같아요.
그리고 async를 안붙여도 될 것 같아요. 혹시 제가 처음 제안한 코드처럼 쓰면 화면이 멈추나요??

2023-10-05 05:11 UTC, guridaek commented on frontend/src/hooks/query/useMissionBranchCreation.ts
> +    mutationFn: async (repoName: string) => postMissionBranchCreation(repoName),
await을 쓰지않으면  `async`는 빼도 되지않나요??

2023-10-05 05:28 UTC, tkdrb12 commented on frontend/src/hooks/query/useFeedbackToSupporter.ts
> +    },
다른 mutation 함수는 반영했는데 해당 파일은 저장하지 않고 push를 했었네요
누락된 부분 다시 반영했습니다

2023-10-05 05:32 UTC, tkdrb12 commented on frontend/src/hooks/query/useMissionBranchCreation.ts
> +    mutationFn: async (repoName: string) => postMissionBranchCreation(repoName),
원래는 비동기 처리 기능을 하는 함수에는 명시적으로 async를 붙일 생각이었습니다.
다른 코드 예시들을 보니 굳이 붙일 필요가 없는 것 같아 제거했습니다

2023-10-05 05:33 UTC, tkdrb12 commented on frontend/src/App.tsx
> +            <Suspense fallback={<div></div>}>
추가했습니다

2023-10-05 05:33 UTC, tkdrb12 commented on frontend/src/pages/MainPage.tsx
> +              fetchNextPage={fetchNextPage}
제거했습니다

2023-10-05 06:29 UTC, guridaek approved these changes

2023-10-05 07:50 UTC, gyeongza commented on frontend/src/hooks/query/useRunnerPostList.ts
> +    queryFn: ({ pageParam }) => getRunnerPost(PAGE_LIMIT, reviewStatus, pageParam, tagName).then((res) => res),
```javascript
queryFn: ({ pageParam }) => getRunnerPost(PAGE_LIMIT, reviewStatus, pageParam, tagName).then((res) => res),
```

요 부분에서 then 물어본겁니당 ㅎㅎ

2023-10-05 07:51 UTC, gyeongza approved these changes
코멘트 확인이요~

2023-10-05 07:54 UTC, merged