알림창, 마이페이지 드롭다운 공용 컴포넌트 구현
woowacourse-teams/2023-baton pull request #613
Opened 2023-10-02 16:04 UTC by gyeongza

## 관련이슈

- resolved #601 

## 참고사항
- [x] 드롭다운 컴포넌트 구현
- [ ] 회원탈퇴 버튼 추가
- [x] 서포터, 러너 마이페이지 분리하기

회원탈퇴 버튼은 어디에다가 넣어야될지 잘 모르겠어서 우선 비워뒀습니다..

--- 

## Dropdown 공용 컴포넌트

```javascript
interface Props extends React.HTMLProps<HTMLDivElement> {
  trigger: React.ReactNode;
  children: React.ReactNode;
  isDropdownOpen: boolean;
  gapFromTrigger: string;
  onClose: () => void;
}

const Dropdown = ({ trigger, children, isDropdownOpen, gapFromTrigger, onClose }: Props) => {
  return (
    <>
      <S.DropdownContainer>
        {trigger} // 드롭다운을 트리거시킬 요소 (알림 아이콘, 프로필 아이콘 등)
        {isDropdownOpen ? (
          <>
            <S.DropdownMenuContainer $gapFromTrigger={gapFromTrigger}>{children}</S.DropdownMenuContainer> // 드롭다운 메뉴에 들어갈 children 컴포넌트
            <S.BackDrop onClick={onClose} />
          </>
        ) : null}
      </S.DropdownContainer>
    </>
  );
};
```

## 드롭다운 컴포넌트 적용 예시
![스크린샷 2023-10-03 오전 12 51 41](https://github.com/woowacourse-teams/2023-baton/assets/62369936/a3e584dd-11d3-490e-9aae-b146c9e62329)
![스크린샷 2023-10-03 오전 12 51 56](https://github.com/woowacourse-teams/2023-baton/assets/62369936/8aa090ed-5112-487a-bc18-ea7e42407e73)

![Oct-03-2023 00-58-56](https://github.com/woowacourse-teams/2023-baton/assets/62369936/802a82c0-1cc3-44ee-ac9f-cab47e3d4e40)
* 로그아웃시 기존에는 isLogin 상태가 Header 안에서 바뀌어서 바로 로그아웃 버튼이 나왔는데 드롭다운에 로그아웃 버튼이 들어가면서 상태가 바로 반영이 안되어서 우선 reload를 사용함. 리액트 쿼리 도입하면서 해결 가능 할 듯

2023-10-02 16:15 UTC, gyeongza commented
마이페이지 분리 때문에 테스트가 통과 안됐군요.. 테스트 짜서 다시 올리겠습니다 🥲

2023-10-05 07:56 UTC, tkdrb12 approved these changes

2023-10-10 02:02 UTC, tkdrb12 submitted a review, later dismissed

2023-10-10 02:16 UTC, guridaek requested changes

2023-10-10 02:16 UTC, guridaek commented on frontend/src/hooks/query/useSelectionSupporter.ts
>      mutationFn: async ({ runnerPostId, supporterId }) => patchProposedSupporterSelection(runnerPostId, supporterId),
async 제거해주세요!

2023-10-10 02:16 UTC, guridaek commented on frontend/src/layout/Header.tsx
> +  const { data: notificationList } = useNotification();
여기에도 props로 isLogin을 내려줘서 enabled를 설정해주면 좋을 것 같아요

2023-10-10 02:21 UTC, guridaek requested changes

2023-10-10 02:21 UTC, guridaek commented on frontend/src/components/NotificationDropdown/NotificationDropdown.tsx
> +    }
읽은 상태면 보이지 않게 해주세용

2023-10-10 07:22 UTC, merged