알람 기능 구현 (이벤트 발행 및 구독, 알람 조회, 알람 삭제, 알람 업데이트)
woowacourse-teams/2023-baton pull request #625
Opened 2023-10-07 14:09 UTC by hyena0608

## 관련이슈

- resolved #624

## 참고사항

- [x] 러너 게시글에 서포터 지원시 이벤트 발행
- [x] 러너 게시글에 서포터 확정시 이벤트 발행
- [x] 러너 게시글 리뷰 완료로 상태 변경시 이벤트 발행
- [x] 로그인된 사용자 알람 목록 조회 API
- [x] 알람 삭제 API
- [x] 알람 읽음 여부 업데이트 API
- [x] 초 단위 삭제를 위한 BaseEntity를 상속한 TruncatedBaseEntity 구현
- [x] flyway 버전 추가 (알람 테이블 생성, 알람 내 member_id 외래키 제약조건 추가)
- [x] CreatedAt 목킹 문제 해결

## 볼만한 곳

### 🟩 RunnerPostCommandService 이벤트 발행 장소

- 러너 게시글에 서포터가 지원할 때 `RunnerPostApplySupporterEvent` 발행
- 러너 게시글에 러너가 서포터를 확정할 때 `RunnerPostAssignSupporterEvent` 발행
- 러너 게시글 리뷰 상태가 리뷰 완료로 업데이트 될 때 `RunnerPostReviewStatusDoneEvent` 발행

<br>
<br>
<br>

### 🟩 RunnerPostCommandService 내부 이벤트 발행 테스트

- `RunnerPostCommandServiceEventTest`

이벤트 발생시 이벤트 발행 카운트를 기록하여 테스트를 검증합니다.

`@RecordApplicationEvents` 를 이용하여 이벤트를 기록합니다.

`ApplicationEvents`를 주입받아 아래와 같이 예상하는 이벤트 클래스를 넣어 발행된 수를 알 수 있습니다.

```java
final int eventPublishedCount = (int) applicationEvents.stream(RunnerPostAssignSupporterEvent.class).count();

assertThat(eventPublishedCount).isOne();
```

<br>
<br>
<br>

### 🟩 AlarmEventListener 구현

- 이벤트 3개 구독
  - RunnerPostApplySupporterEvent
  - RunnerPostAssignSupporterEvent
  - RunnerPostReviewStatusDoneEvent

- 트랜잭션 전파 및 이벤트 리스너 시작
  - 상위 트랜잭션에서 커밋 되었을 경우 시작한다.
  - 새로운 트랜잭션으로 진행한다.

```java
@TransactionalEventListener(phase = AFTER_COMMIT)
@Transactional(propagation = REQUIRES_NEW)
```

<br>
<br>
<br>

### 🟩 AlarmEventListener 테스트

서비스 테스트 조건으로 테스트를 진행했습니다.

알람 이벤트 리스너 내부에서 알람이 생성됩니다.

반환이 void로 알람에 대한 검증을 하기 위해서는 알람을 받은 사용자 식별자값으로 알람 목록을 조회합니다.

예상된 알람 수만 존재하는지 검증한 후에 통과할 경우 내부 검증을 진행하도록 했습니다.

```java
class AlarmEventListenerTest extends RepositoryTestConfig {

    private AlarmEventListener alarmEventListener;

    @Autowired
    private AlarmQueryRepository alarmQueryRepository;

    @BeforeEach
    void setUp(@Autowired AlarmCommandRepository alarmCommandRepository,
               @Autowired RunnerPostQueryRepository runnerPostQueryRepository) {
        alarmEventListener = new AlarmEventListener(alarmCommandRepository, runnerPostQueryRepository);
    }

// ...
}
```

```java
assertSoftly(softly -> {
    softly.assertThat(actualAlarms).hasSize(1);
    final Alarm actual = actualAlarms.get(0);
    assertThat(actual.getId()).isPositive();
    assertThat(actual.getAlarmTitle().getValue()).isEqualTo(expectedAlarmTitle);
    assertThat(actual.getAlarmMessage().getValue()).isEqualTo(expectedAlarmMessage);
    assertThat(actual.getAlarmType()).isEqualTo(expectedAlarmType);
    assertThat(actual.getAlarmReferencedId().getValue()).isEqualTo(expectedReferencedId);
    assertThat(actual.getIsRead().getValue()).isEqualTo(expectedIsRead);
    assertThat(actual.getMember()).isEqualTo(expectedMember);
});
```

<br>
<br>
<br>

### 🟩 TruncatedBaseEntity extends BaseEntity

의견 받은 것을 구현했습니다.

BaseEntity를 상속받아 TruncatedBaseEntity를 구현했고 이를 Alarm이 상속하고 있습니다.

```java
public class Alarm extends TruncatedBaseEntity
```

`TruncatedBaseEntity`는 getter를 오버라이딩하고 있습니다.

```java
public abstract class TruncatedBaseEntity extends BaseEntity {  
  
    @Override  
    public LocalDateTime getCreatedAt() {  
        return super.getCreatedAt().truncatedTo(ChronoUnit.MINUTES);  
    }  
  
    @Override  
    public LocalDateTime getDeletedAt() {  
        return super.getDeletedAt().truncatedTo(ChronoUnit.MINUTES);  
    }  
  
    @Override  
    public LocalDateTime getUpdatedAt() {  
        return super.getUpdatedAt().truncatedTo(ChronoUnit.MINUTES);  
    }  
}
```

원하는 것처럼 초단위가 삭제되는 것을 인수테스트에서도 확인할 수 있었습니다.

🚨🚨🚨 하지만 Restdocs 테스트에서 목킹할 때는 주의해야할 점이 있습니다. 🚨🚨🚨

목킹으로 진행하는 테스트의 경우 JpaAuditing이 동작하지 않아 createdAt이 null인 상태입니다.

기존대로 아래처럼 목킹을 진행할 경우 NPE가 발생합니다.

```java
// 잘못된 목킹

Alarm spyAlarm = spy(alarm);

when(spyAlarm.getCreatedAt())
    .thenReturn(LocalDateTime.now().truncatedTo(ChronoUnit.MINUTES))
```

이러한 형태의 목킹은 실제 `spyAlarm` 내부에 `createdAt`을 직접 호출하고 반환은 목킹한 값을 줍니다.

이 때 `TruncatedBaseEntity` 내부에 `getCreatedAt()` 메서드를 보면 `truncatedTo()`을 호출하고 있습니다.

```java
    @Override  
    public LocalDateTime getCreatedAt() {  
        return super.getCreatedAt().truncatedTo(ChronoUnit.MINUTES);  
    }  
```

예상할 수 있듯이 `null.truncatedTo()`의 형태로 NPE가 발생합니다.

그래서 아래와 같이 실제 메서드를 호출하지 않도록 목킹해야 합니다.

```java
// 잘된 목킹

doReturn(LocalDateTime.now().truncatedTo(ChronoUnit.MINUTES))  
        .when(spyAlarm)  
        .getCreatedAt();
```

현재 목킹하는 부분은 외부 API와 의존되는 부분과 restdocs 정도라 큰 문제가 없을 수 있지만 위 방식과 다르게 해결할 수 있다면 좋을 거 같습니다.

이유는 사용하다보면 코드에서 냄새가 스멀스멀 👃 올라온다고 하네요.

![](https://i.imgur.com/pSAipIq.png)

<br>
<br>
<br>

### 🟩 flyway 버전 추가 (알람 테이블 생성, 알람 외래키 제약조건 추가)

테이블 생성과 제약조건 추가를 두 가지로 나눠서 작성했습니다.

`
```sql
CREATE TABLE alarm  
(  
    id            BIGINT            NOT NULL AUTO_INCREMENT PRIMARY KEY,  
    title         VARCHAR(255)      NOT NULL,  
    message       VARCHAR(255)      NOT NULL,  
    alarm_type    VARCHAR(255)      NOT NULL,  
    is_read       bit default false NOT NULL,  
    referenced_id BIGINT            NOT NULL,  
    member_id     BIGINT            NOT NULL,  
    created_at    DATETIME(6)       NOT NULL,  
    updated_at    DATETIME(6)       NOT NULL,  
    deleted_at    DATETIME(6),  
);
```

```sql
ALTER TABLE alarm  
    ADD CONSTRAINT fk_alarm_to_member  
        FOREIGN KEY (member_id) REFERENCES member (id);
```

2023-10-08 05:51 UTC, shb03323 commented on backend/baton/src/main/java/touch/baton/domain/alarm/command/event/AlarmEventListener.java
> +    @Transactional(propagation = REQUIRES_NEW)
이벤트 리스너 자체가 부가적인 트랜잭션을 요구하는건 명백해보이는데, 클래스 위에 트랜잭션 관련 어노테이션을 붙이면 어때요?

2023-10-08 05:57 UTC, shb03323 commented on backend/baton/src/main/java/touch/baton/domain/alarm/command/vo/AlarmText.java
> +    MESSAGE_REFERENCED_BY_RUNNER_POST("관련 게시글 - %s");
나중에 쪽지가 생기게 되었을 때 runner_post 관련 텍스트와 쪽지 관련 텍스트가 같은 파일에 위치하게 될 것 같아요.

2023-10-08 06:01 UTC, shb03323 commented on backend/baton/src/main/java/touch/baton/domain/alarm/command/vo/AlarmText.java
> +    MESSAGE_REFERENCED_BY_RUNNER_POST("관련 게시글 - %s");
RunnerPost 관련 AlarmText라는 의미로 RunnerPostAlarmText로 enum 명을 바꾸면 어때요?

또, AlarmType과 연관시켜서 AlarmText를 정의하는건 어때요? AlarmType에 따라서 다른 텍스트를 선택하도록 하는 것이 더 자연스러워 보여요. 지금 AlarmType은 상수파일 같아서요ㅠㅠ

2023-10-08 06:17 UTC, shb03323 commented on backend/baton/src/main/java/touch/baton/domain/alarm/command/vo/AlarmText.java
> +    MESSAGE_REFERENCED_BY_RUNNER_POST("관련 게시글 - %s");
mvc 할 때 HandlerMapper, HandlerAdapter 비슷하게용

2023-10-08 06:20 UTC, shb03323 commented on backend/baton/src/main/java/touch/baton/domain/alarm/command/vo/AlarmTitle.java
> +    }
AlarmTItle이 데이터베이스에 저장될 때 3가지 경우로만 저장되고 있습니다. 고정되어있는 title 이라면 enum 자료형으로 데이터베이스를 칼럼을 지정하는 것은 어떤가요? 속도 측면, 관리 측면에서 더 편할 것 같아서요.

2023-10-08 06:21 UTC, shb03323 commented on backend/baton/src/main/java/touch/baton/domain/alarm/command/vo/AlarmText.java
> +    MESSAGE_REFERENCED_BY_RUNNER_POST("관련 게시글 - %s");
완전 비슷하진 않지만 망나니 형님의 enum 활용입니다.
https://mangkyu.tistory.com/74

2023-10-08 06:23 UTC, shb03323 commented on backend/baton/src/main/java/touch/baton/domain/alarm/command/event/AlarmEventListener.java
> +    }
요즘 제가 함수형 인터페이스에 미쳐있긴 한데요...
3개의 트랜잭션 모두 중복인 것 같아요.

함수형 인터페이스로 중복코드 줄여보는 건 어때요?

2023-10-08 06:28 UTC, shb03323 commented on backend/baton/src/main/java/touch/baton/domain/alarm/query/repository/AlarmQueryRepository.java
> +        """)
jpql에 limit가 동작하지 않는 것으로 알고 있는데, 정확히 동작하나용?

2023-10-08 06:28 UTC, shb03323 commented on backend/baton/src/main/java/touch/baton/domain/alarm/query/repository/AlarmQueryRepository.java
> +        """)
native query나 querydsl 써야할 것 같아서요

2023-10-08 06:39 UTC, shb03323 commented on backend/baton/src/main/java/touch/baton/domain/runnerpost/command/service/RunnerPostCommandService.java
> +        eventPublisher.publishEvent(new RunnerPostApplySupporterEvent(foundRunnerPost.getId()));
진짜 신기하네요 이거

2023-10-08 06:44 UTC, shb03323 commented on backend/baton/src/test/java/touch/baton/document/alarm/delete/AlarmDeleteApiTest.java
> +        willDoNothing().given(alarmCommandService).deleteAlarmByMember(any(Member.class), anyLong());
when 파트에 있으니깐 요건 어때용
```suggestion
    doNothing().when(alarmCommandService).deleteAlarmByMember(any(Member.class), anyLong());
```

2023-10-08 06:45 UTC, shb03323 commented on backend/baton/src/test/java/touch/baton/document/alarm/delete/AlarmDeleteApiTest.java
> +        willDoNothing().given(alarmCommandService).deleteAlarmByMember(any(Member.class), anyLong());
근데 지금까지 전체적으로 when, given 위치 지키지 않고 했어서... 이야기해보아야할 것 같아요.

2023-10-08 06:52 UTC, shb03323 commented on backend/baton/src/test/java/touch/baton/domain/runnerpost/command/service/RunnerPostCommandServiceEventTest.java
> +        final int eventPublishedCount = (int) applicationEvents.stream(RunnerPostApplySupporterEvent.class).count();
```suggestion
        final int eventPublishedCount = Long.valueOf(applicationEvents.stream(RunnerPostApplySupporterEvent.class).count()).intValue();
```
타입캐스팅보다 이렇게 하거나, 그냥 Long 값으로 받는 건 어때요? 타입캐스팅하면 int 범위 벗어나도 예외가 안터져서요...

2023-10-08 06:52 UTC, shb03323 commented on backend/baton/src/test/java/touch/baton/domain/runnerpost/command/service/RunnerPostCommandServiceEventTest.java
> +        final int eventPublishedCount = (int) applicationEvents.stream(RunnerPostAssignSupporterEvent.class).count();
마찬가지222

2023-10-08 06:52 UTC, shb03323 commented on backend/baton/src/test/java/touch/baton/domain/runnerpost/command/service/RunnerPostCommandServiceEventTest.java
> +        final int eventPublishedCount = (int) applicationEvents.stream(RunnerPostReviewStatusDoneEvent.class).count();
요기도

2023-10-08 06:54 UTC, shb03323 commented on backend/baton/src/test/java/touch/baton/document/alarm/read/AlarmReadWithLoginedMemberApiTest.java
> +                .getCreatedAt();
모킹 짱짱맨

2023-10-08 06:58 UTC, shb03323 requested changes
미친 PR 메시지 감탄했습니다. 한번 보고 코드 보니깐 술술 읽혔습니다. 고생하셨습니다.
하지만 제안 사항이 있어서용!!

아 그리고,,,, big 제안사항인데, 보통 alarm은 시계가 울리는것이나 경고주는거라고 생각해왔었어요. notification이 정보를 전달하는 알림인 것이죠. 그래서 fcm도 보면 notification으로 명시하고 있습니다.

흠 계속 고민했었는데 이제야 말해서 죄송합니다. 그래도 초반에 논의하면 좋을 것 같아서요.
아래는 gpt 형님의 말씀입니다.

>"푸시 알람"을 구현하려고 할 때 "alarm"과 "notification" 두 용어 모두 사용될 수 있으나, 그 뜻과 상황에 따라 약간의 차이가 있습니다. 어떤 단어를 선택할지 판단하기 위해 두 용어의 의미와 일반적인 사용 사례를 간략히 살펴보겠습니다.

>Alarm:
"알람"은 특정 시간 또는 조건에 대한 경고 또는 알림을 나타내는 데 사용됩니다. 예를 들어, 아침에 일어나기 위한 시계 알람이나 특정 조건을 충족할 때 알려주는 경고 알람 등이 있습니다.
"알람"이 발생하면 즉시 대응이 필요한 경우가 많습니다.

>Notification:
"알림"은 일반적으로 사용자에게 정보를 전달하는 데 사용됩니다. 이는 시스템 이벤트, 메시지, 업데이트 등 다양한 종류의 정보를 포함할 수 있습니다.
사용자가 즉시 대응할 필요는 없지만 알림을 확인하면 추가 정보나 액션을 취할 수 있습니다.
따라서 선택할 단어는 구현하려는 기능과 해당 알람/알림의 목적에 따라 결정됩니다.

>사용자에게 중요한 이벤트나 조건에 대해 즉시 대응이 필요한 알림을 제공하려면 "alarm"을 선택하는 것이 좋습니다.
사용자에게 정보를 제공하거나 선택적으로 대응할 수 있는 알림을 제공하려면 "notification"을 선택하는 것이 좋습니다.
물론, 프로젝트의 컨텍스트나 팀 내에서의 합의에 따라 이러한 가이드라인이 약간 달라질 수 있습니다.

2023-10-09 01:29 UTC, cookienc requested changes
정성스런 PR 덕분에 빨리 파악할 수 있었습니다. 감사합니당🙇‍♂️🙇‍♂️
+2500줄이지만 리뷰할게 별로 없네요.
역시 헤나신👍👍
코멘트 남겨놨으니까 한 번 확인해주세용

2023-10-09 01:29 UTC, cookienc commented on backend/baton/src/main/java/touch/baton/domain/alarm/command/repository/AlarmCommandRepository.java
> +    void updateIsReadTrueByMemberId(@Param("alarmId") Long alarmId);
요견 변경감지 쓰면 문제가 될게 있을까요?

2023-10-09 01:29 UTC, cookienc commented on backend/baton/src/main/java/touch/baton/domain/alarm/command/event/AlarmEventListener.java
> +                .alarmMessage(new AlarmMessage(String.format(MESSAGE_REFERENCED_BY_RUNNER_POST.getText(), runnerPost.getTitle().getValue())))
아 이러면 AlaramTitle이랑 모든게 다 enum으로 바꿔야하네요. 이건 좀 고민~

2023-10-09 01:29 UTC, cookienc commented on backend/baton/src/main/java/touch/baton/domain/alarm/command/vo/AlarmTitle.java
> +    }
Title 같은 경우는 view랑 많이 연결되어 있을것 같아서 변경될 여지가 많아 보여요. 할꺼면 enum으로 class를 만들고 데이터는 기존이랑 동일하게 varchar로 가시는게 어떤가요?

2023-10-09 01:29 UTC, cookienc commented on backend/baton/src/main/java/touch/baton/domain/common/TruncatedBaseEntity.java
> +public abstract class TruncatedBaseEntity extends BaseEntity {
굿굿

2023-10-09 01:29 UTC, cookienc commented on backend/baton/src/test/java/touch/baton/assure/alarm/query/AlarmQueryAssuredTest.java
> +        for (int 저장될_알람_카운트_수 = 1; 저장될_알람_카운트_수 <= 5; 저장될_알람_카운트_수++) {
좋은데요?

2023-10-09 01:29 UTC, cookienc commented on backend/baton/src/test/java/touch/baton/domain/runnerpost/command/service/RunnerPostCommandServiceEventTest.java
> +        final int eventPublishedCount = (int) applicationEvents.stream(RunnerPostApplySupporterEvent.class).count();
```suggestion
        final int eventPublishedCount = applicationEvents.stream(RunnerPostApplySupporterEvent.class).mapToInt(e -> 1).sum();
```
javadoc에 나온것처럼 하면 이런 방법도 있음
근데 long으로 그냥 쓰는게 더 좋을거 가탕요

2023-10-09 01:44 UTC, hyena0608 commented on backend/baton/src/main/java/touch/baton/domain/alarm/query/repository/AlarmQueryRepository.java
> +        """)
AlarmQueryRepositoryTest에 테스트 코드 있습니다!
h2, MySQL 둘 다 잘 돌아가고 테스트 코드랑, postman에서 확인했었습니다.

혹시 동작 이상이 예상되는 부분 있으면 말씀해주시면 확인해보겠습니다.

2023-10-09 01:46 UTC, hyena0608 commented on backend/baton/src/main/java/touch/baton/domain/alarm/command/event/AlarmEventListener.java
> +    }
생각이 잘 안되는데 혹시 예시 살짝만 보여주실 수 있나요?

2023-10-09 01:48 UTC, hyena0608 commented on backend/baton/src/main/java/touch/baton/domain/alarm/command/vo/AlarmTitle.java
> +    }
알람 제목이 고정적이지 않을거 같다고 생각했어요.
정책이 확실하게 고정으로 간다면 enum도 좋은거 같아요.

그래도 알람 관련한 부분이 계속해서 추가사항이 있을거라 생각해서 enum으로 하면 이후에 메시지 수정하는데 불편함이 있을거 같아요

2023-10-09 02:03 UTC, hyena0608 commented on backend/baton/src/main/java/touch/baton/domain/alarm/command/vo/AlarmText.java
> +    MESSAGE_REFERENCED_BY_RUNNER_POST("관련 게시글 - %s");
알람 메시지는 확정이 아니라 변경될 수 있어서 한 곳에서 관리했습니다.
class와 enum 중 어떤 거로 만들어 둘까 고민했는데 enum으로 만들게 되면서 저의 의도와 다르게 다른 방식으로 이용할 수 있다라는 생각을 들게한 코드가 된거 같네요 🥲

---

AlarmType은 AlarmTitle이나 AlarmMessage와 연관이 없고 AlarmReferencedId와 연관이 있습니다.
AlarmType 알람과 연관된 타입의 식별자값을 구별하기 위한 필드입니다.

AlarmTitle를  다른 곳에 고정적으로 넣지 않은 부분은 제 의도가 맞습니다.
확실하지 않은 정책에 대해서 고정된 코드가 되는 듯한 느낌을 받아서 일부러 AlarmText를 단순한 상수로만 사용하게 만들었습니다. 

AlarmType에 AlarmTitle을 두게 될 경우에는 일대일로 매핑되거나 필요한 AlarmTitle를 꺼내기 위해서 조회 로직이 추가적으로 들어가야 할 거 같습니다.

2023-10-09 02:14 UTC, hyena0608 commented on backend/baton/src/main/java/touch/baton/domain/alarm/command/event/AlarmEventListener.java
> +    @Transactional(propagation = REQUIRES_NEW)
클래스 수준에 트랜잭션 어노테이션을 붙이는게 괜찮을지 고민됩니다.

이유는 AlarmEventListener 에 있는 메서드들이 각기 다른 트랜잭션 속성을 갖을 수 있기 때문입니다.

현재는 `@Transactional(propagation = REQUIRES_NEW)`로 중복되어 보이지만
실제로는 이후에 언제든지 다른 속성이 들어올 수 있습니다.

구현하면서 이벤트 부분의 트랜잭션 속성은 상황에 맞게 확인하고 적용하기를 의도하기 위해서 일부러 클래스 수준에 작성하지는 않았습니다.

만약 클래스 수준의 `@Transactional`가 있다고 해서 메서드 수준에 트랜잭션 속성을 주지 않는다면 생각과 다르게 기능이 수행될 수도 있습니다.

처음부터 트랜잭션이 없고 필요하다면 속성에 맞게 붙이는게 이후에 코드 작성할 때 정확하게 작성할 수 있지 않을까 생각이 듭니다.

다만 생각해보면 비동기 이벤트가 아니라서 이벤트를 발행하는 곳에서 트랜잭션이 있다면 해당 트랜잭션을 이어서 사용하게 됩니다.

그렇다면 이벤트 리스너 클래스 수준에 트랜잭션이 있다는 것을 명시해줘야 할 거 같다고 생각이 들었습니다.

하지만 이벤트 리스너는 이벤트가 발행되는 지점에서 어떤 일이 있는지 숙지하고 사용하는 것이 되는거 같고
이는 이벤트 의도와 벗어나는거 같아서 기존 코드로 충분하지 않을까 생각합니다.

디투랑 에단 의견을 한 번 더 들어보고 싶네요!

2023-10-09 02:16 UTC, hyena0608 commented on backend/baton/src/main/java/touch/baton/domain/alarm/command/vo/AlarmTitle.java
> +    }
위에서 비슷한 내용으로 커멘트 달아서 링크 첨부할게요 👍

[AlarmType, AlarmTitle, AlarmText 관련한 커멘트](https://github.com/woowacourse-teams/2023-baton/pull/625#discussion_r1349819132)

2023-10-09 02:17 UTC, hyena0608 commented on backend/baton/src/test/java/touch/baton/document/alarm/delete/AlarmDeleteApiTest.java
> +        willDoNothing().given(alarmCommandService).deleteAlarmByMember(any(Member.class), anyLong());
doNothing().when() 굿굿 좋습니다.

2023-10-09 02:18 UTC, hyena0608 commented on backend/baton/src/test/java/touch/baton/domain/runnerpost/command/service/RunnerPostCommandServiceEventTest.java
> +        final int eventPublishedCount = (int) applicationEvents.stream(RunnerPostApplySupporterEvent.class).count();
테스트 코드라서 long으로 그냥 쓰는게 좋을거 같다에 한 표입니다!

2023-10-09 02:21 UTC, hyena0608 commented on backend/baton/src/main/java/touch/baton/domain/alarm/command/repository/AlarmCommandRepository.java
> +    void updateIsReadTrueByMemberId(@Param("alarmId") Long alarmId);
오 진짜 이거 왜 만들었지 생각이 드네요 ㅋㅋㅋ 🥲 굿굿

2023-10-09 02:26 UTC, hyena0608 commented
> 미친 PR 메시지 감탄했습니다. 한번 보고 코드 보니깐 술술 읽혔습니다. 고생하셨습니다. 하지만 제안 사항이 있어서용!!
> 
> 아 그리고,,,, big 제안사항인데, 보통 alarm은 시계가 울리는것이나 경고주는거라고 생각해왔었어요. notification이 정보를 전달하는 알림인 것이죠. 그래서 fcm도 보면 notification으로 명시하고 있습니다.
> 
> 흠 계속 고민했었는데 이제야 말해서 죄송합니다. 그래도 초반에 논의하면 좋을 것 같아서요. 아래는 gpt 형님의 말씀입니다.
> 
> > "푸시 알람"을 구현하려고 할 때 "alarm"과 "notification" 두 용어 모두 사용될 수 있으나, 그 뜻과 상황에 따라 약간의 차이가 있습니다. 어떤 단어를 선택할지 판단하기 위해 두 용어의 의미와 일반적인 사용 사례를 간략히 살펴보겠습니다.
> 
> > Alarm:
> > "알람"은 특정 시간 또는 조건에 대한 경고 또는 알림을 나타내는 데 사용됩니다. 예를 들어, 아침에 일어나기 위한 시계 알람이나 특정 조건을 충족할 때 알려주는 경고 알람 등이 있습니다.
> > "알람"이 발생하면 즉시 대응이 필요한 경우가 많습니다.
> 
> > Notification:
> > "알림"은 일반적으로 사용자에게 정보를 전달하는 데 사용됩니다. 이는 시스템 이벤트, 메시지, 업데이트 등 다양한 종류의 정보를 포함할 수 있습니다.
> > 사용자가 즉시 대응할 필요는 없지만 알림을 확인하면 추가 정보나 액션을 취할 수 있습니다.
> > 따라서 선택할 단어는 구현하려는 기능과 해당 알람/알림의 목적에 따라 결정됩니다.
> 
> > 사용자에게 중요한 이벤트나 조건에 대해 즉시 대응이 필요한 알림을 제공하려면 "alarm"을 선택하는 것이 좋습니다.
> > 사용자에게 정보를 제공하거나 선택적으로 대응할 수 있는 알림을 제공하려면 "notification"을 선택하는 것이 좋습니다.
> > 물론, 프로젝트의 컨텍스트나 팀 내에서의 합의에 따라 이러한 가이드라인이 약간 달라질 수 있습니다.

아침에 일어나기 위한 시계 ⏰ ㅋㅋㅋㅋㅋㅋㅋㅋㅋ
바로 Notification으로 달려보겠습니다 🏃🏃‍♀️ 굿굿

2023-10-10 06:02 UTC, cookienc approved these changes
고생했습니당👍👍

2023-10-10 07:45 UTC, shb03323 approved these changes
LGTM

2023-10-10 07:47 UTC, merged