태그 목록 검색 기능 리팩터링
woowacourse-teams/2023-baton pull request #637
Opened 2023-10-10 08:10 UTC by hyena0608

## 관련이슈

- resolved #635

## 참고사항

- [x] TagQuerySupport 내부 사용하지 않는 메서드 삭제
- [x] TagQueryRepository -> TagQuerydslRepository
  - [x] querydsl를 이용한 태그 목록 검색 기능 구현

2023-10-10 10:16 UTC, cookienc approved these changes

2023-10-10 13:39 UTC, shb03323 commented on backend/baton/src/test/java/touch/baton/assure/repository/TestTagQueryRepository.java
> +            """)
limit!

2023-10-10 13:39 UTC, shb03323 commented on backend/baton/src/test/java/touch/baton/assure/repository/TestTagQueryRepository.java
> +            """)
의도한건가요?

2023-10-10 13:40 UTC, shb03323 commented on backend/baton/src/test/java/touch/baton/domain/tag/query/repository/TagQuerydslRepositoryTest.java
> +        );
테스트 되게 꼼꼼하군요.

2023-10-10 13:41 UTC, shb03323 requested changes
jpql limit 관련 있어서요. 내일 이야기해보아요.

2023-10-11 06:04 UTC, cookienc submitted a review, later dismissed
LGTM!🙇‍♂️🙇

2023-10-11 07:29 UTC, shb03323 approved these changes
LGTM!

2023-10-11 07:54 UTC, merged