러너 리뷰 요청 게시글 생성 version-test
woowacourse-teams/2023-baton pull request #94
Opened 2023-07-25 08:48 UTC by cookienc

## 관련이슈

- resolved #85 

## 참고사항
- RunnerPost와 Suppoter의 관계를 `ManyToOne`으로 변경했습니다.

2023-07-25 08:56 UTC, shb03323 commented on backend/baton/src/main/java/touch/baton/domain/runnerpost/controller/RunnerPostController.java
> +        Runner runner = runnerService.readRunnerWithMember(1L);
final 해주세요.

2023-07-25 08:58 UTC, shb03323 commented on backend/baton/src/main/java/touch/baton/domain/runnerpost/service/dto/RunnerPostCreateTestRequest.java
> +                                          @JsonFormat(pattern = "yyyy-MM-dd'T'HH:mm")
타임존 넣어야할듯.

2023-07-25 08:58 UTC, shb03323 requested changes
반영해주세요.

2023-07-25 09:03 UTC, shb03323 approved these changes
LGTM

2023-07-25 09:22 UTC, hyena0608 approved these changes

2023-07-25 17:35 UTC, eunbii0213 requested changes
반영부탁드립니다!

2023-07-25 17:35 UTC, eunbii0213 commented on backend/baton/src/main/java/touch/baton/domain/runnerpost/service/RunnerPostService.java
> +        List<Tag> toSaveTags = new ArrayList<>();
toSaveTags에 final이 사라졌어용

2023-07-26 00:30 UTC, cookienc commented on backend/baton/src/main/java/touch/baton/domain/runnerpost/service/RunnerPostService.java
> +        List<Tag> toSaveTags = new ArrayList<>();
수정했습니다! 매의 눈👀

2023-07-26 01:09 UTC, eunbii0213 approved these changes
수고하셨어용 ㅎㅎㅎㅎ

2023-07-26 01:09 UTC, eunbii0213 commented on backend/baton/src/main/java/touch/baton/domain/runnerpost/service/RunnerPostService.java
>          List<Tag> toSaveTags = new ArrayList<>();
여기두 final 빠진 것 같아요!!

2023-07-26 01:10 UTC, merged